# Generated by Django 4.2.30 on 2026-05-22 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_qualityinspection'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='qualityinspection',
            new_name='inventory_q_status_545a96_idx',
            old_name='inventory_qu_status_8c4f25_idx',
        ),
        migrations.RenameIndex(
            model_name='qualityinspection',
            new_name='inventory_q_product_1ccbf3_idx',
            old_name='inventory_qu_product_a2dc90_idx',
        ),
        migrations.RenameIndex(
            model_name='qualityinspection',
            new_name='inventory_q_seller__0efa09_idx',
            old_name='inventory_qu_seller_8d0fd4_idx',
        ),
    ]
