# Generated by Django 4.2.30 on 2026-05-22 03:03

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_search_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_25e057_idx',
            old_name='orders_order_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='releasecondition',
            new_name='orders_rele_order_i_52db44_idx',
            old_name='orders_rele_order_i_1c2c83_idx',
        ),
        migrations.RenameIndex(
            model_name='releasecondition',
            new_name='orders_rele_status_39cba1_idx',
            old_name='orders_rele_status_32b474_idx',
        ),
        migrations.RenameIndex(
            model_name='releaseconditionproof',
            new_name='orders_rele_conditi_df0e65_idx',
            old_name='orders_rele_conditi_6cbf7f_idx',
        ),
        migrations.RenameIndex(
            model_name='wishlistitem',
            new_name='orders_wish_buyer_i_47f405_idx',
            old_name='orders_wish_buyer_i_1a3d4a_idx',
        ),
        migrations.RenameIndex(
            model_name='wishlistitem',
            new_name='orders_wish_product_47dca4_idx',
            old_name='orders_wish_product_08f3d3_idx',
        ),
        migrations.AlterField(
            model_name='releaseconditionproof',
            name='file',
            field=models.FileField(upload_to=apps.orders.models._release_proof_upload_to),
        ),
    ]
