# Generated by Django 4.2.30 on 2026-05-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_payment_and_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extension_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='extension_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
