# Generated by Django 4.2.30 on 2026-06-01 16:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_shipment_perf_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='warehouserelease',
            new_name='orders_ware_seller__053c26_idx',
            old_name='orders_whrel_seller_created_idx',
        ),
        migrations.RenameIndex(
            model_name='warehouserelease',
            new_name='orders_ware_warehou_0998bf_idx',
            old_name='orders_whrel_wh_created_idx',
        ),
        migrations.RenameIndex(
            model_name='warehouserelease',
            new_name='orders_ware_status_bffce9_idx',
            old_name='orders_whrel_status_created_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
