# Generated by Django 4.2.30 on 2026-05-22 03:03

import apps.catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_product_search_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listingrequest',
            new_name='catalog_lis_seller__d8b4b6_idx',
            old_name='catalog_list_seller__8c99fd_idx',
        ),
        migrations.RenameIndex(
            model_name='listingrequestphoto',
            new_name='catalog_lis_listing_b24639_idx',
            old_name='catalog_list_listing__ccfe1a_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_sku_2c4c34_idx',
            old_name='catalog_product_sku_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='catalog_pro_hs_code_384230_idx',
            old_name='catalog_product_hscode_idx',
        ),
        migrations.AlterField(
            model_name='listingrequest',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='listingrequestphoto',
            name='file',
            field=models.FileField(upload_to=apps.catalog.models._listing_request_upload_to),
        ),
    ]
