# Generated by Django 4.2.30 on 2026-05-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmedia",
            name="storage_key",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="productmedia",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]

