# Generated by Django 4.2.30 on 2026-05-25 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_productmedia_storage_key_and_url_blank"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="detail_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="productmedia",
            name="variation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media",
                to="catalog.productvariation",
            ),
        ),
    ]

