# Generated by Django 4.2.30 on 2026-05-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_product_detail_config_and_media_variation"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmedia",
            name="title",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="productmedia",
            name="content_type",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="productmedia",
            name="size_bytes",
            field=models.BigIntegerField(default=0),
        ),
    ]

