# Generated by Django 4.2.30 on 2026-06-01 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0017_listingrequest_product_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('shipped', 'Shipped'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('tracking_number', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InboundRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_expected', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameIndex(
            model_name='warehousestock',
            new_name='catalog_war_seller__837fea_idx',
            old_name='wh_stock_seller_wh_idx',
        ),
        migrations.RenameIndex(
            model_name='warehousestock',
            new_name='catalog_war_product_bbbb4b_idx',
            old_name='wh_stock_product_wh_idx',
        ),
        migrations.RemoveField(
            model_name='listingrequest',
            name='product_meta',
        ),
        migrations.AddField(
            model_name='listingrequest',
            name='compliance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listingrequest',
            name='compliance_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingrequest',
            name='inspected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listingrequest',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_inspections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listingrequest',
            name='stage',
            field=models.CharField(choices=[('samples', 'Samples'), ('compliance', 'Compliance'), ('inspection', 'Inspection'), ('live', 'Live'), ('done', 'Done')], default='samples', max_length=16),
        ),
        migrations.AddField(
            model_name='inboundrequestitem',
            name='inbound_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalog.inboundrequest'),
        ),
        migrations.AddField(
            model_name='inboundrequestitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product'),
        ),
        migrations.AddField(
            model_name='inboundrequestitem',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.productvariation'),
        ),
        migrations.AddField(
            model_name='inboundrequest',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inboundrequest',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_requests', to='catalog.warehouse'),
        ),
        migrations.AddIndex(
            model_name='inboundrequest',
            index=models.Index(fields=['seller', 'status'], name='catalog_inb_seller__249a08_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundrequest',
            index=models.Index(fields=['warehouse', 'status'], name='catalog_inb_warehou_68c53e_idx'),
        ),
    ]
