# Generated by Django 4.2.30 on 2026-06-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_inboundrequest_inboundrequestitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingrequest',
            name='stage',
            field=models.CharField(choices=[('samples', 'Samples'), ('compliance', 'Compliance'), ('inspection', 'Inspection'), ('inbound', 'Inbound'), ('live', 'Live'), ('done', 'Done')], default='samples', max_length=16),
        ),
    ]
