# Generated by Django 4.2.30 on 2026-06-01 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_listingrequest_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundrequest',
            name='listing_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbound_request', to='catalog.listingrequest'),
        ),
    ]
