# Generated by Django 4.2.30 on 2026-06-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_inboundrequest_listing_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingrequest',
            name='product_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
