# Generated by Django 4.2.30 on 2026-05-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_search_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('getting_started', 'Getting started as seller'), ('listing_approval', 'Listing & approval'), ('fulfillment', 'Fulfillment pipeline'), ('payouts', 'Payouts & earnings'), ('shipping', 'Shipping & logistics'), ('disputes', 'Disputes & protection'), ('analytics', 'Analytics & trends'), ('account_security', 'Account & security'), ('business_tools', 'Business tools'), ('plans_pricing', 'Plans & pricing')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('body', models.JSONField(blank=True, default=list)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('tip', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='adminuinotificationstate',
            new_name='accounts_ad_user_id_f00c42_idx',
            old_name='accounts_adm_user_id_4f6a75_idx',
        ),
        migrations.RenameIndex(
            model_name='adminuinotificationstate',
            new_name='accounts_ad_user_id_6f161f_idx',
            old_name='accounts_adm_user_id_3b5d51_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_status_2e3176_idx',
            old_name='accounts_user_status_joined_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_role_3c46aa_idx',
            old_name='accounts_user_role_joined_idx',
        ),
        migrations.AlterField(
            model_name='kycdocument',
            name='kind',
            field=models.CharField(choices=[('passport', 'Passport'), ('driving_license', 'Driving License'), ('id_card', 'ID Card'), ('bank_statement', 'Bank Statement'), ('business_license', 'Business License'), ('business_registration', 'Business Registration'), ('utility_bill', 'Utility Bill'), ('iso_9001', 'ISO 9001'), ('gmp', 'GMP Compliance'), ('export_license', 'Export License'), ('product_safety', 'Product Safety'), ('id_doc_1', 'ID Document 1'), ('id_doc_2', 'ID Document 2'), ('proof_of_address', 'Proof of Address'), ('business_doc_1', 'Business Document 1'), ('business_doc_2', 'Business Document 2')], max_length=32),
        ),
    ]
