# Generated by Django 4.2.30 on 2026-05-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_helparticle_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language_preference",
            field=models.CharField(
                blank=True,
                choices=[("en", "English"), ("zh", "Chinese")],
                default="en",
                max_length=16,
            ),
        ),
    ]

