# Generated by Django 4.2.30 on 2026-06-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_sellerprofile_warehouse_location_buyeraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('admin', 'Admin'), ('partner', 'Partner'), ('logistics', 'Logistics')], default='buyer', max_length=16),
        ),
    ]
