// ─── Category Data: 3-Stage Hierarchy ─────────────────────────────────────
// Main Category → Subcategory → Products
// Every icon chosen for instant recognition — even a child understands it.

export interface Product {
  id: string;
  name: string;
  icon: string;
  price: string;
}

export interface SubCategory {
  id: string;
  label: string;
  icon: string;
  products: Product[];
}

export interface Category {
  id: string;
  label: string;
  icon: string;
  subcategories: SubCategory[];
}

export const categories: Category[] = [
  // ── VEHICLES ───────────────────────────────────────────────────────────
  {
    id: "vehicles",
    label: "Vehicles",
    icon: "car",
    subcategories: [
      { id: "suv", label: "SUV", icon: "suv", products: [
        { id: "v-suv-1", name: "Compact Crossover", icon: "compass", price: "$28K – $38K" },
        { id: "v-suv-2", name: "Family SUV", icon: "users", price: "$35K – $52K" },
        { id: "v-suv-3", name: "Off-Road SUV", icon: "mountain", price: "$42K – $65K" },
        { id: "v-suv-4", name: "Luxury SUV", icon: "crown", price: "$60K – $95K" },
        { id: "v-suv-5", name: "Hybrid SUV", icon: "leaf", price: "$38K – $58K" },
        { id: "v-suv-6", name: "Electric SUV", icon: "zap", price: "$45K – $80K" },
        { id: "v-suv-7", name: "Subcompact SUV", icon: "minimize", price: "$22K – $32K" },
        { id: "v-suv-8", name: "Performance SUV", icon: "gauge", price: "$55K – $110K" },
        { id: "v-suv-9", name: "3-Row SUV", icon: "layers", price: "$40K – $65K" },
        { id: "v-suv-10", name: "Rugged SUV", icon: "shield", price: "$38K – $60K" },
        { id: "v-suv-11", name: "Diesel SUV", icon: "fuel", price: "$40K – $68K" },
        { id: "v-suv-12", name: "Coupe SUV", icon: "car-front", price: "$48K – $85K" },
        { id: "v-suv-13", name: "Armored SUV", icon: "shield", price: "$80K – $250K" },
        { id: "v-suv-14", name: "Adventure SUV", icon: "tent", price: "$36K – $55K" },
        { id: "v-suv-15", name: "City SUV", icon: "building", price: "$25K – $40K" },
        { id: "v-suv-16", name: "Premium Midsize", icon: "star", price: "$45K – $72K" },
      ]},
      { id: "jeep", label: "Jeep", icon: "jeep", products: [
        { id: "v-jp-1", name: "Trail 4×4", icon: "mountain", price: "$38K – $55K" },
        { id: "v-jp-2", name: "Open-Top Jeep", icon: "sun", price: "$35K – $48K" },
        { id: "v-jp-3", name: "Utility Jeep", icon: "wrench", price: "$32K – $44K" },
        { id: "v-jp-4", name: "Sahara Edition", icon: "compass", price: "$42K – $58K" },
        { id: "v-jp-5", name: "Rock Crawler", icon: "anchor", price: "$45K – $65K" },
        { id: "v-jp-6", name: "Military Spec", icon: "shield", price: "$50K – $80K" },
        { id: "v-jp-7", name: "Overland Jeep", icon: "map", price: "$48K – $72K" },
        { id: "v-jp-8", name: "Sport Jeep", icon: "gauge", price: "$30K – $42K" },
        { id: "v-jp-9", name: "Arctic Jeep", icon: "snowflake", price: "$52K – $75K" },
        { id: "v-jp-10", name: "Desert Runner", icon: "sun", price: "$44K – $62K" },
        { id: "v-jp-11", name: "Expedition Jeep", icon: "globe", price: "$55K – $82K" },
        { id: "v-jp-12", name: "Classic Jeep", icon: "history", price: "$25K – $60K" },
        { id: "v-jp-13", name: "Lifted Jeep", icon: "mountain", price: "$48K – $70K" },
        { id: "v-jp-14", name: "Diesel Jeep", icon: "fuel", price: "$40K – $58K" },
      ]},
      { id: "pickup-truck", label: "Pickup Truck", icon: "pickup-truck", products: [
        { id: "v-pt-1", name: "Work Truck", icon: "hard-hat", price: "$30K – $45K" },
        { id: "v-pt-2", name: "Crew Cab", icon: "users", price: "$38K – $56K" },
        { id: "v-pt-3", name: "Electric Pickup", icon: "zap", price: "$50K – $80K" },
        { id: "v-pt-4", name: "Heavy Duty", icon: "weight", price: "$45K – $70K" },
        { id: "v-pt-5", name: "Off-Road Pickup", icon: "mountain", price: "$42K – $65K" },
        { id: "v-pt-6", name: "Luxury Pickup", icon: "crown", price: "$55K – $85K" },
        { id: "v-pt-7", name: "Compact Truck", icon: "minimize", price: "$25K – $38K" },
        { id: "v-pt-8", name: "Diesel Pickup", icon: "fuel", price: "$40K – $62K" },
        { id: "v-pt-9", name: "Extended Bed", icon: "ruler", price: "$35K – $52K" },
        { id: "v-pt-10", name: "Hybrid Pickup", icon: "leaf", price: "$42K – $68K" },
        { id: "v-pt-11", name: "Flatbed Truck", icon: "layers", price: "$32K – $50K" },
        { id: "v-pt-12", name: "Single Cab", icon: "car", price: "$24K – $36K" },
        { id: "v-pt-13", name: "Sport Pickup", icon: "gauge", price: "$38K – $62K" },
        { id: "v-pt-14", name: "Ranch Truck", icon: "fence", price: "$30K – $48K" },
        { id: "v-pt-15", name: "Trail Pickup", icon: "compass", price: "$40K – $60K" },
      ]},
      { id: "monster-truck", label: "Monster Truck", icon: "monster-truck", products: [
        { id: "v-mt-1", name: "Show Monster", icon: "star", price: "$80K – $150K" },
        { id: "v-mt-2", name: "Racing Monster", icon: "gauge", price: "$100K – $200K" },
        { id: "v-mt-3", name: "Mud Runner", icon: "droplets", price: "$60K – $120K" },
        { id: "v-mt-4", name: "Freestyle Monster", icon: "sparkles", price: "$90K – $180K" },
        { id: "v-mt-5", name: "Exhibition Build", icon: "eye", price: "$120K – $250K" },
        { id: "v-mt-6", name: "Youth Monster", icon: "toy-brick", price: "$40K – $80K" },
        { id: "v-mt-7", name: "Custom Monster", icon: "wrench", price: "$150K – $300K" },
        { id: "v-mt-8", name: "Arena Crusher", icon: "flame", price: "$110K – $220K" },
        { id: "v-mt-9", name: "Mega Monster", icon: "rocket", price: "$200K – $400K" },
        { id: "v-mt-10", name: "Vintage Monster", icon: "history", price: "$80K – $180K" },
        { id: "v-mt-11", name: "Electric Monster", icon: "zap", price: "$150K – $350K" },
        { id: "v-mt-12", name: "Mini Monster", icon: "minimize", price: "$30K – $60K" },
        { id: "v-mt-13", name: "Stunt Monster", icon: "flag", price: "$120K – $260K" },
        { id: "v-mt-14", name: "Desert Monster", icon: "sun", price: "$100K – $200K" },
      ]},
      { id: "van", label: "Van", icon: "van", products: [
        { id: "v-vn-1", name: "Cargo Van", icon: "box", price: "$32K – $48K" },
        { id: "v-vn-2", name: "Passenger Van", icon: "users", price: "$35K – $55K" },
        { id: "v-vn-3", name: "Camper Van", icon: "tent", price: "$55K – $90K" },
        { id: "v-vn-4", name: "Delivery Van", icon: "package", price: "$28K – $42K" },
        { id: "v-vn-5", name: "Electric Van", icon: "zap", price: "$45K – $75K" },
        { id: "v-vn-6", name: "Refrigerated Van", icon: "snowflake", price: "$38K – $60K" },
        { id: "v-vn-7", name: "Minivan", icon: "baby", price: "$30K – $50K" },
        { id: "v-vn-8", name: "Luxury Van", icon: "crown", price: "$60K – $120K" },
        { id: "v-vn-9", name: "Conversion Van", icon: "wrench", price: "$50K – $85K" },
        { id: "v-vn-10", name: "Panel Van", icon: "square", price: "$26K – $40K" },
        { id: "v-vn-11", name: "Ambulance Van", icon: "cross", price: "$60K – $120K" },
        { id: "v-vn-12", name: "Food Truck Van", icon: "utensils", price: "$40K – $80K" },
        { id: "v-vn-13", name: "Window Van", icon: "eye", price: "$30K – $50K" },
        { id: "v-vn-14", name: "Off-Grid Van", icon: "mountain", price: "$65K – $100K" },
      ]},
      { id: "caravan", label: "Caravan", icon: "caravan", products: [
        { id: "v-cv-1", name: "Travel Trailer", icon: "map-pin", price: "$25K – $50K" },
        { id: "v-cv-2", name: "Motorhome", icon: "home", price: "$80K – $200K" },
        { id: "v-cv-3", name: "Pop-Up Camper", icon: "tent", price: "$12K – $25K" },
        { id: "v-cv-4", name: "Fifth Wheel", icon: "link", price: "$40K – $100K" },
        { id: "v-cv-5", name: "Teardrop Trailer", icon: "droplet", price: "$8K – $20K" },
        { id: "v-cv-6", name: "Class A RV", icon: "crown", price: "$100K – $400K" },
        { id: "v-cv-7", name: "Toy Hauler", icon: "gamepad", price: "$35K – $80K" },
        { id: "v-cv-8", name: "Truck Camper", icon: "truck", price: "$15K – $40K" },
        { id: "v-cv-9", name: "Airstream", icon: "sparkles", price: "$50K – $150K" },
        { id: "v-cv-10", name: "Off-Road Trailer", icon: "mountain", price: "$30K – $80K" },
        { id: "v-cv-11", name: "Class B RV", icon: "star", price: "$60K – $150K" },
        { id: "v-cv-12", name: "Micro Camper", icon: "minimize", price: "$5K – $15K" },
        { id: "v-cv-13", name: "Luxury RV", icon: "gem", price: "$200K – $600K" },
        { id: "v-cv-14", name: "Expedition Trailer", icon: "globe", price: "$25K – $70K" },
      ]},
      { id: "open-roof", label: "Open Roof", icon: "open-roof", products: [
        { id: "v-or-1", name: "Roadster", icon: "wind", price: "$45K – $70K" },
        { id: "v-or-2", name: "Convertible", icon: "sun", price: "$38K – $65K" },
        { id: "v-or-3", name: "Targa Top", icon: "circle", price: "$55K – $90K" },
        { id: "v-or-4", name: "Drop-Top GT", icon: "gauge", price: "$65K – $120K" },
        { id: "v-or-5", name: "Cabrio Luxury", icon: "crown", price: "$80K – $150K" },
        { id: "v-or-6", name: "Sport Spider", icon: "flame", price: "$50K – $95K" },
        { id: "v-or-7", name: "Retro Ragtop", icon: "history", price: "$35K – $60K" },
        { id: "v-or-8", name: "Electric Cabrio", icon: "zap", price: "$55K – $100K" },
        { id: "v-or-9", name: "Classic Vert", icon: "history", price: "$40K – $120K" },
        { id: "v-or-10", name: "Beach Cruiser", icon: "waves", price: "$30K – $55K" },
        { id: "v-or-11", name: "Speedster", icon: "rocket", price: "$70K – $140K" },
        { id: "v-or-12", name: "Touring Cabrio", icon: "map", price: "$50K – $90K" },
        { id: "v-or-13", name: "Luxury Droptop", icon: "diamond", price: "$100K – $250K" },
      ]},
      { id: "car", label: "Car", icon: "car", products: [
        { id: "v-cr-1", name: "Sedan", icon: "car", price: "$22K – $35K" },
        { id: "v-cr-2", name: "Electric Car", icon: "zap", price: "$35K – $60K" },
        { id: "v-cr-3", name: "Hybrid", icon: "leaf", price: "$28K – $45K" },
        { id: "v-cr-4", name: "Compact", icon: "minimize", price: "$18K – $28K" },
        { id: "v-cr-5", name: "Luxury Sedan", icon: "crown", price: "$50K – $90K" },
        { id: "v-cr-6", name: "Station Wagon", icon: "users", price: "$30K – $48K" },
        { id: "v-cr-7", name: "Hatchback", icon: "car-front", price: "$20K – $32K" },
        { id: "v-cr-8", name: "Executive Car", icon: "briefcase", price: "$45K – $80K" },
        { id: "v-cr-9", name: "City Car", icon: "building", price: "$15K – $25K" },
        { id: "v-cr-10", name: "Diesel Sedan", icon: "fuel", price: "$24K – $40K" },
        { id: "v-cr-11", name: "Sport Sedan", icon: "gauge", price: "$35K – $65K" },
        { id: "v-cr-12", name: "Micro Car", icon: "minimize", price: "$12K – $20K" },
        { id: "v-cr-13", name: "Hydrogen Car", icon: "droplet", price: "$50K – $80K" },
        { id: "v-cr-14", name: "Taxi Sedan", icon: "map-pin", price: "$20K – $35K" },
        { id: "v-cr-15", name: "Armored Sedan", icon: "shield", price: "$80K – $200K" },
        { id: "v-cr-16", name: "Estate Car", icon: "home", price: "$32K – $55K" },
      ]},
      { id: "sports-car", label: "Sports Car", icon: "sports-car", products: [
        { id: "v-sc-1", name: "Supercar", icon: "rocket", price: "$120K – $300K" },
        { id: "v-sc-2", name: "GT Coupe", icon: "gauge", price: "$60K – $120K" },
        { id: "v-sc-3", name: "Track Special", icon: "flag", price: "$80K – $200K" },
        { id: "v-sc-4", name: "Muscle Car", icon: "flame", price: "$40K – $75K" },
        { id: "v-sc-5", name: "Rally Edition", icon: "mountain", price: "$55K – $100K" },
        { id: "v-sc-6", name: "Electric Sports", icon: "zap", price: "$70K – $150K" },
        { id: "v-sc-7", name: "Mid-Engine Coupe", icon: "cog", price: "$90K – $180K" },
        { id: "v-sc-8", name: "Lightweight Racer", icon: "feather", price: "$65K – $130K" },
        { id: "v-sc-9", name: "Drift Car", icon: "wind", price: "$35K – $70K" },
        { id: "v-sc-10", name: "Time Attack", icon: "timer", price: "$45K – $90K" },
        { id: "v-sc-11", name: "Turbo Coupe", icon: "fan", price: "$50K – $95K" },
        { id: "v-sc-12", name: "Retro Sport", icon: "history", price: "$40K – $85K" },
        { id: "v-sc-13", name: "AWD Sports", icon: "compass", price: "$55K – $110K" },
        { id: "v-sc-14", name: "Grand Tourer", icon: "globe", price: "$70K – $150K" },
      ]},
      { id: "exotic-car", label: "Exotic Car", icon: "exotic-car", products: [
        { id: "v-ec-1", name: "Hypercar", icon: "rocket", price: "$500K – $3M" },
        { id: "v-ec-2", name: "Limited Edition", icon: "gem", price: "$300K – $2M" },
        { id: "v-ec-3", name: "Vintage Exotic", icon: "history", price: "$200K – $5M" },
        { id: "v-ec-4", name: "Bespoke Build", icon: "pen-tool", price: "$1M – $10M" },
        { id: "v-ec-5", name: "Track Hypercar", icon: "flag", price: "$800K – $5M" },
        { id: "v-ec-6", name: "One-of-One", icon: "diamond", price: "$2M – $20M" },
        { id: "v-ec-7", name: "Heritage Model", icon: "crown", price: "$400K – $8M" },
        { id: "v-ec-8", name: "Electric Hyper", icon: "zap", price: "$600K – $4M" },
        { id: "v-ec-9", name: "Concept Car", icon: "lightbulb", price: "$1M – $15M" },
        { id: "v-ec-10", name: "Auction Classic", icon: "star", price: "$500K – $50M" },
        { id: "v-ec-11", name: "Supercar GT", icon: "gauge", price: "$250K – $1.5M" },
        { id: "v-ec-12", name: "Carbon Edition", icon: "feather", price: "$400K – $3M" },
        { id: "v-ec-13", name: "Roadster Exotic", icon: "wind", price: "$300K – $2M" },
        { id: "v-ec-14", name: "Royal Edition", icon: "crown", price: "$1M – $8M" },
      ]},
    ],
  },

  // ── INDUSTRIAL ─────────────────────────────────────────────────────────
  {
    id: "industrial",
    label: "Industrial",
    icon: "factory",
    subcategories: [
      { id: "machinery", label: "Machinery", icon: "cog", products: [
        { id: "i-mc-1", name: "CNC Machine", icon: "cpu", price: "$15K – $80K" },
        { id: "i-mc-2", name: "Lathe", icon: "circle", price: "$5K – $30K" },
        { id: "i-mc-3", name: "Hydraulic Press", icon: "gauge", price: "$8K – $50K" },
        { id: "i-mc-4", name: "Conveyor Belt", icon: "move-horizontal", price: "$3K – $20K" },
        { id: "i-mc-5", name: "Milling Machine", icon: "cog", price: "$10K – $60K" },
        { id: "i-mc-6", name: "Injection Molder", icon: "box", price: "$20K – $150K" },
        { id: "i-mc-7", name: "Punch Press", icon: "target", price: "$12K – $70K" },
        { id: "i-mc-8", name: "3D Printer Ind.", icon: "printer", price: "$8K – $200K" },
        { id: "i-mc-9", name: "Laser Cutter", icon: "zap", price: "$15K – $100K" },
        { id: "i-mc-10", name: "CNC Router", icon: "cog", price: "$8K – $50K" },
        { id: "i-mc-11", name: "Plasma Cutter", icon: "flame", price: "$5K – $40K" },
        { id: "i-mc-12", name: "Waterjet Cutter", icon: "droplets", price: "$30K – $200K" },
        { id: "i-mc-13", name: "Bending Machine", icon: "flip-horizontal", price: "$10K – $80K" },
        { id: "i-mc-14", name: "Grinding Machine", icon: "sparkles", price: "$5K – $40K" },
        { id: "i-mc-15", name: "EDM Machine", icon: "zap", price: "$20K – $150K" },
      ]},
      { id: "raw-materials", label: "Raw Materials", icon: "layers", products: [
        { id: "i-rm-1", name: "Steel Sheets", icon: "layers", price: "$500 – $5K/ton" },
        { id: "i-rm-2", name: "Aluminum Bars", icon: "ruler", price: "$800 – $4K/ton" },
        { id: "i-rm-3", name: "Copper Wire", icon: "cable", price: "$2K – $8K/ton" },
        { id: "i-rm-4", name: "Polymers", icon: "flask", price: "$600 – $3K/ton" },
        { id: "i-rm-5", name: "Carbon Fiber", icon: "feather", price: "$10 – $50/kg" },
        { id: "i-rm-6", name: "Titanium Plate", icon: "shield", price: "$5K – $20K/ton" },
        { id: "i-rm-7", name: "Brass Rods", icon: "cylinder", price: "$1K – $6K/ton" },
        { id: "i-rm-8", name: "Stainless Steel", icon: "sparkles", price: "$1.5K – $7K/ton" },
        { id: "i-rm-9", name: "Rubber Compound", icon: "circle", price: "$800 – $3K/ton" },
      ]},
      { id: "chemicals", label: "Chemicals", icon: "flask", products: [
        { id: "i-ch-1", name: "Industrial Solvents", icon: "droplet", price: "$200 – $2K" },
        { id: "i-ch-2", name: "Adhesive Resin", icon: "link", price: "$300 – $1.5K" },
        { id: "i-ch-3", name: "Coating Chemicals", icon: "paintbrush", price: "$400 – $3K" },
        { id: "i-ch-4", name: "Industrial Acids", icon: "flask", price: "$150 – $1K" },
        { id: "i-ch-5", name: "Cleaning Agents", icon: "sparkles", price: "$100 – $800" },
        { id: "i-ch-6", name: "Lubricants", icon: "droplets", price: "$200 – $1.5K" },
        { id: "i-ch-7", name: "Catalysts", icon: "atom", price: "$500 – $5K" },
        { id: "i-ch-8", name: "Pigments & Dyes", icon: "palette", price: "$300 – $2K" },
      ]},
      { id: "packaging", label: "Packaging", icon: "package", products: [
        { id: "i-pk-1", name: "Corrugated Boxes", icon: "box", price: "$0.5 – $5/unit" },
        { id: "i-pk-2", name: "Shrink Film", icon: "square", price: "$80 – $400/roll" },
        { id: "i-pk-3", name: "Pallets", icon: "layers", price: "$15 – $60/unit" },
        { id: "i-pk-4", name: "Bubble Wrap", icon: "circle", price: "$30 – $150/roll" },
        { id: "i-pk-5", name: "Foam Inserts", icon: "shield", price: "$2 – $15/unit" },
        { id: "i-pk-6", name: "Tape & Strapping", icon: "paperclip", price: "$10 – $80/roll" },
        { id: "i-pk-7", name: "Crates & Bins", icon: "container", price: "$20 – $200" },
        { id: "i-pk-8", name: "Label Rolls", icon: "tag", price: "$15 – $100/roll" },
        { id: "i-pk-9", name: "Vacuum Bags", icon: "wind", price: "$5 – $40/pack" },
      ]},
      { id: "safety-gear", label: "Safety Gear", icon: "shield", products: [
        { id: "i-sg-1", name: "Hard Hats", icon: "hard-hat", price: "$15 – $80" },
        { id: "i-sg-2", name: "Safety Goggles", icon: "glasses", price: "$10 – $50" },
        { id: "i-sg-3", name: "Safety Gloves", icon: "hand", price: "$8 – $40" },
        { id: "i-sg-4", name: "Hi-Vis Vests", icon: "shirt", price: "$12 – $35" },
        { id: "i-sg-5", name: "Steel-Toe Boots", icon: "footprints", price: "$60 – $200" },
        { id: "i-sg-6", name: "Ear Protection", icon: "ear", price: "$10 – $60" },
        { id: "i-sg-7", name: "Face Shields", icon: "shield", price: "$15 – $80" },
        { id: "i-sg-8", name: "Respirators", icon: "air-vent", price: "$20 – $150" },
        { id: "i-sg-9", name: "Fall Harness", icon: "link", price: "$80 – $400" },
      ]},
      { id: "tools-industrial", label: "Power Tools", icon: "wrench", products: [
        { id: "i-pt-1", name: "Drill Press", icon: "drill", price: "$500 – $5K" },
        { id: "i-pt-2", name: "Angle Grinder", icon: "sparkles", price: "$80 – $600" },
        { id: "i-pt-3", name: "Welding Machine", icon: "flame", price: "$300 – $8K" },
        { id: "i-pt-4", name: "Air Compressor", icon: "wind", price: "$200 – $3K" },
        { id: "i-pt-5", name: "Plasma Cutter", icon: "zap", price: "$500 – $5K" },
        { id: "i-pt-6", name: "Band Saw", icon: "scissors", price: "$400 – $3K" },
        { id: "i-pt-7", name: "Heat Gun", icon: "thermometer", price: "$30 – $200" },
        { id: "i-pt-8", name: "Riveting Tool", icon: "bolt", price: "$50 – $400" },
      ]},
      { id: "heavy-equip", label: "Heavy Equipment", icon: "truck", products: [
        { id: "i-he-1", name: "Excavator", icon: "shovel", price: "$50K – $500K" },
        { id: "i-he-2", name: "Bulldozer", icon: "mountain", price: "$80K – $400K" },
        { id: "i-he-3", name: "Crane", icon: "anchor", price: "$100K – $1M" },
        { id: "i-he-4", name: "Forklift", icon: "forklift", price: "$20K – $80K" },
        { id: "i-he-5", name: "Backhoe Loader", icon: "pickaxe", price: "$40K – $150K" },
        { id: "i-he-6", name: "Dump Truck", icon: "truck", price: "$80K – $300K" },
        { id: "i-he-7", name: "Concrete Mixer", icon: "circle", price: "$30K – $120K" },
        { id: "i-he-8", name: "Road Roller", icon: "construction", price: "$25K – $100K" },
        { id: "i-he-9", name: "Skid Steer", icon: "wrench", price: "$20K – $60K" },
      ]},
      { id: "automation", label: "Automation", icon: "cpu", products: [
        { id: "i-au-1", name: "Robotic Arm", icon: "bot", price: "$25K – $150K" },
        { id: "i-au-2", name: "PLC Controller", icon: "circuit-board", price: "$500 – $5K" },
        { id: "i-au-3", name: "Sensor Array", icon: "scan-eye", price: "$200 – $2K" },
        { id: "i-au-4", name: "Vision System", icon: "eye", price: "$5K – $30K" },
        { id: "i-au-5", name: "Motor Drives", icon: "zap", price: "$300 – $3K" },
        { id: "i-au-6", name: "Conveyor System", icon: "move-horizontal", price: "$5K – $50K" },
        { id: "i-au-7", name: "Pick & Place Bot", icon: "hand", price: "$15K – $80K" },
        { id: "i-au-8", name: "AGV Robot", icon: "truck", price: "$20K – $100K" },
        { id: "i-au-9", name: "SCADA System", icon: "monitor", price: "$10K – $60K" },
      ]},
    ],
  },

  // ── HARDWARE ───────────────────────────────────────────────────────────
  {
    id: "hardware",
    label: "Hardware",
    icon: "hammer",
    subcategories: [
      { id: "hand-tools", label: "Hand Tools", icon: "wrench", products: [
        { id: "h-ht-1", name: "Screwdriver Set", icon: "wrench", price: "$15 – $80" },
        { id: "h-ht-2", name: "Pliers", icon: "link", price: "$10 – $45" },
        { id: "h-ht-3", name: "Tape Measure", icon: "ruler", price: "$8 – $30" },
        { id: "h-ht-4", name: "Socket Set", icon: "cog", price: "$25 – $150" },
        { id: "h-ht-5", name: "Wrenches", icon: "nut", price: "$12 – $80" },
        { id: "h-ht-6", name: "Hammer Set", icon: "hammer", price: "$15 – $60" },
        { id: "h-ht-7", name: "Chisel Set", icon: "pen-tool", price: "$10 – $50" },
        { id: "h-ht-8", name: "Clamps", icon: "grip", price: "$8 – $40" },
        { id: "h-ht-9", name: "Level Tool", icon: "scale", price: "$10 – $60" },
      ]},
      { id: "power-tools", label: "Power Tools", icon: "zap", products: [
        { id: "h-pw-1", name: "Cordless Drill", icon: "drill", price: "$60 – $300" },
        { id: "h-pw-2", name: "Circular Saw", icon: "circle", price: "$80 – $400" },
        { id: "h-pw-3", name: "Orbital Sander", icon: "square", price: "$40 – $200" },
        { id: "h-pw-4", name: "Jigsaw", icon: "sparkles", price: "$50 – $250" },
        { id: "h-pw-5", name: "Impact Driver", icon: "zap", price: "$70 – $300" },
        { id: "h-pw-6", name: "Router", icon: "cog", price: "$80 – $350" },
        { id: "h-pw-7", name: "Reciprocating Saw", icon: "scissors", price: "$60 – $250" },
        { id: "h-pw-8", name: "Nail Gun", icon: "target", price: "$80 – $400" },
        { id: "h-pw-9", name: "Table Saw", icon: "layers", price: "$200 – $1.5K" },
      ]},
      { id: "fasteners", label: "Fasteners", icon: "bolt", products: [
        { id: "h-fs-1", name: "Bolts & Nuts", icon: "bolt", price: "$5 – $50/box" },
        { id: "h-fs-2", name: "Wood Screws", icon: "tree", price: "$4 – $30/box" },
        { id: "h-fs-3", name: "Wall Anchors", icon: "anchor", price: "$6 – $25/box" },
        { id: "h-fs-4", name: "Nails", icon: "hammer", price: "$3 – $20/box" },
        { id: "h-fs-5", name: "Rivets", icon: "circle", price: "$5 – $30/box" },
        { id: "h-fs-6", name: "Washers", icon: "nut", price: "$3 – $15/box" },
        { id: "h-fs-7", name: "Toggle Bolts", icon: "link", price: "$8 – $35/box" },
        { id: "h-fs-8", name: "Concrete Screws", icon: "mountain", price: "$6 – $28/box" },
      ]},
      { id: "plumbing", label: "Plumbing", icon: "droplet", products: [
        { id: "h-pl-1", name: "Pipe Fittings", icon: "link", price: "$2 – $30" },
        { id: "h-pl-2", name: "Faucets", icon: "droplet", price: "$30 – $300" },
        { id: "h-pl-3", name: "Valves", icon: "circle", price: "$10 – $80" },
        { id: "h-pl-4", name: "Water Heater", icon: "heater", price: "$200 – $1.5K" },
        { id: "h-pl-5", name: "Sump Pump", icon: "waves", price: "$80 – $400" },
        { id: "h-pl-6", name: "Drain Pipes", icon: "cylinder", price: "$5 – $40" },
        { id: "h-pl-7", name: "Toilet Parts", icon: "wrench", price: "$10 – $60" },
        { id: "h-pl-8", name: "Shower Heads", icon: "shower-head", price: "$20 – $200" },
        { id: "h-pl-9", name: "Water Filters", icon: "filter", price: "$30 – $300" },
      ]},
      { id: "electrical", label: "Electrical", icon: "plug", products: [
        { id: "h-el-1", name: "Wire & Cable", icon: "cable", price: "$20 – $200/roll" },
        { id: "h-el-2", name: "Switches", icon: "toggle-left", price: "$5 – $40" },
        { id: "h-el-3", name: "Circuit Breakers", icon: "shield", price: "$15 – $100" },
        { id: "h-el-4", name: "Outlets", icon: "plug", price: "$3 – $25" },
        { id: "h-el-5", name: "Conduit", icon: "cylinder", price: "$10 – $60" },
        { id: "h-el-6", name: "Junction Boxes", icon: "box", price: "$5 – $30" },
        { id: "h-el-7", name: "Light Fixtures", icon: "lightbulb", price: "$15 – $200" },
        { id: "h-el-8", name: "Dimmer Switch", icon: "sun", price: "$10 – $50" },
        { id: "h-el-9", name: "Electrical Tape", icon: "layers", price: "$3 – $15" },
      ]},
      { id: "paint", label: "Paint & Finish", icon: "paintbrush", products: [
        { id: "h-pa-1", name: "Wall Paint", icon: "paint-bucket", price: "$25 – $80/gal" },
        { id: "h-pa-2", name: "Primer", icon: "droplet", price: "$20 – $50/gal" },
        { id: "h-pa-3", name: "Wood Stain", icon: "palette", price: "$15 – $45" },
        { id: "h-pa-4", name: "Spray Paint", icon: "spray-can", price: "$5 – $15/can" },
        { id: "h-pa-5", name: "Varnish", icon: "sparkles", price: "$15 – $50" },
        { id: "h-pa-6", name: "Epoxy Floor", icon: "layers", price: "$40 – $150/gal" },
        { id: "h-pa-7", name: "Texture Paint", icon: "hand", price: "$30 – $80/gal" },
        { id: "h-pa-8", name: "Paint Brushes", icon: "paintbrush", price: "$5 – $40/set" },
        { id: "h-pa-9", name: "Rollers & Trays", icon: "paint-roller", price: "$8 – $30/set" },
      ]},
      { id: "lumber", label: "Lumber", icon: "tree", products: [
        { id: "h-lu-1", name: "Plywood", icon: "square", price: "$30 – $80/sheet" },
        { id: "h-lu-2", name: "Hardwood", icon: "tree", price: "$4 – $15/bf" },
        { id: "h-lu-3", name: "MDF Board", icon: "layers", price: "$25 – $60/sheet" },
        { id: "h-lu-4", name: "Timber Beams", icon: "ruler", price: "$5 – $20/lf" },
        { id: "h-lu-5", name: "Pine Boards", icon: "tree-pine", price: "$3 – $12/bf" },
        { id: "h-lu-6", name: "Cedar Planks", icon: "leaf", price: "$6 – $18/bf" },
        { id: "h-lu-7", name: "OSB Sheets", icon: "square", price: "$20 – $50/sheet" },
        { id: "h-lu-8", name: "Bamboo Planks", icon: "sprout", price: "$4 – $12/sqft" },
        { id: "h-lu-9", name: "Walnut Boards", icon: "tree", price: "$8 – $25/bf" },
        { id: "h-lu-10", name: "Birch Plywood", icon: "layers", price: "$35 – $90/sheet" },
        { id: "h-lu-11", name: "Teak Wood", icon: "crown", price: "$12 – $40/bf" },
        { id: "h-lu-12", name: "Reclaimed Wood", icon: "rotate-ccw", price: "$5 – $20/bf" },
        { id: "h-lu-13", name: "Treated Lumber", icon: "shield", price: "$4 – $14/bf" },
        { id: "h-lu-14", name: "Moulding & Trim", icon: "ruler", price: "$2 – $10/lf" },
      ]},
      { id: "adhesives", label: "Adhesives", icon: "paperclip", products: [
        { id: "h-ad-1", name: "Wood Glue", icon: "tree", price: "$5 – $25" },
        { id: "h-ad-2", name: "Epoxy", icon: "link", price: "$8 – $40" },
        { id: "h-ad-3", name: "Sealant", icon: "shield", price: "$6 – $20" },
        { id: "h-ad-4", name: "Mounting Tape", icon: "paperclip", price: "$4 – $15" },
        { id: "h-ad-5", name: "Super Glue", icon: "zap", price: "$3 – $12" },
        { id: "h-ad-6", name: "Contact Cement", icon: "layers", price: "$8 – $30" },
        { id: "h-ad-7", name: "Spray Adhesive", icon: "spray-can", price: "$8 – $25" },
        { id: "h-ad-8", name: "Caulk", icon: "droplet", price: "$4 – $15" },
        { id: "h-ad-9", name: "Hot Glue Gun", icon: "flame", price: "$10 – $50" },
        { id: "h-ad-10", name: "Foam Tape", icon: "layers", price: "$4 – $18" },
        { id: "h-ad-11", name: "Thread Locker", icon: "bolt", price: "$5 – $20" },
        { id: "h-ad-12", name: "Silicone Sealant", icon: "shield", price: "$6 – $25" },
        { id: "h-ad-13", name: "Welding Adhesive", icon: "zap", price: "$8 – $35" },
        { id: "h-ad-14", name: "Tile Adhesive", icon: "square", price: "$10 – $40" },
      ]},
    ],
  },

  // ── ELECTRONICS ────────────────────────────────────────────────────────
  {
    id: "electronics",
    label: "Electronics",
    icon: "monitor",
    subcategories: [
      { id: "laptops", label: "Laptops", icon: "laptop", products: [
        { id: "e-lp-1", name: "Gaming Laptop", icon: "gamepad", price: "$900 – $3K" },
        { id: "e-lp-2", name: "Business Laptop", icon: "briefcase", price: "$700 – $2K" },
        { id: "e-lp-3", name: "Ultrabook", icon: "feather", price: "$800 – $1.8K" },
        { id: "e-lp-4", name: "Workstation", icon: "cpu", price: "$1.5K – $5K" },
        { id: "e-lp-5", name: "Chromebook", icon: "globe", price: "$200 – $600" },
        { id: "e-lp-6", name: "2-in-1 Laptop", icon: "tablet", price: "$500 – $1.5K" },
        { id: "e-lp-7", name: "Student Laptop", icon: "graduation-cap", price: "$300 – $800" },
        { id: "e-lp-8", name: "Creative Pro", icon: "palette", price: "$1.2K – $4K" },
        { id: "e-lp-9", name: "Rugged Laptop", icon: "shield", price: "$1K – $3K" },
        { id: "e-lp-10", name: "Mini Laptop", icon: "minimize", price: "$400 – $900" },
        { id: "e-lp-11", name: "AI Laptop", icon: "bot", price: "$1K – $3K" },
        { id: "e-lp-12", name: "Fanless Laptop", icon: "wind", price: "$600 – $1.5K" },
        { id: "e-lp-13", name: "Linux Laptop", icon: "cpu", price: "$500 – $2K" },
        { id: "e-lp-14", name: "Touch Laptop", icon: "hand", price: "$700 – $2K" },
        { id: "e-lp-15", name: "Refurbished Pro", icon: "rotate-ccw", price: "$300 – $1.2K" },
      ]},
      { id: "phones", label: "Phones", icon: "smartphone", products: [
        { id: "e-ph-1", name: "Flagship Phone", icon: "star", price: "$800 – $1.5K" },
        { id: "e-ph-2", name: "Budget Phone", icon: "tag", price: "$150 – $400" },
        { id: "e-ph-3", name: "Rugged Phone", icon: "shield", price: "$300 – $800" },
        { id: "e-ph-4", name: "Foldable Phone", icon: "smartphone", price: "$1K – $2K" },
        { id: "e-ph-5", name: "Camera Phone", icon: "camera", price: "$600 – $1.2K" },
        { id: "e-ph-6", name: "Gaming Phone", icon: "gamepad", price: "$500 – $1K" },
        { id: "e-ph-7", name: "Compact Phone", icon: "minimize", price: "$400 – $800" },
        { id: "e-ph-8", name: "5G Phone", icon: "signal", price: "$350 – $900" },
        { id: "e-ph-9", name: "Senior Phone", icon: "users", price: "$50 – $200" },
        { id: "e-ph-10", name: "Business Phone", icon: "briefcase", price: "$400 – $1K" },
        { id: "e-ph-11", name: "Kids Phone", icon: "baby", price: "$80 – $250" },
        { id: "e-ph-12", name: "Satellite Phone", icon: "antenna", price: "$500 – $2K" },
        { id: "e-ph-13", name: "Dual-SIM Phone", icon: "layers", price: "$200 – $600" },
        { id: "e-ph-14", name: "Refurbished Phone", icon: "rotate-ccw", price: "$100 – $500" },
      ]},
      { id: "tablets", label: "Tablets", icon: "tablet", products: [
        { id: "e-tb-1", name: "Standard Tablet", icon: "tablet", price: "$300 – $800" },
        { id: "e-tb-2", name: "Drawing Tablet", icon: "pen-tool", price: "$400 – $1.5K" },
        { id: "e-tb-3", name: "E-Reader", icon: "book-open", price: "$100 – $300" },
        { id: "e-tb-4", name: "Kids Tablet", icon: "toy-brick", price: "$80 – $200" },
        { id: "e-tb-5", name: "Pro Tablet", icon: "star", price: "$800 – $2K" },
        { id: "e-tb-6", name: "Mini Tablet", icon: "minimize", price: "$200 – $500" },
        { id: "e-tb-7", name: "Rugged Tablet", icon: "shield", price: "$400 – $1.2K" },
        { id: "e-tb-8", name: "Android Tablet", icon: "layers", price: "$150 – $600" },
        { id: "e-tb-9", name: "Gaming Tablet", icon: "gamepad", price: "$400 – $1K" },
        { id: "e-tb-10", name: "Note Tablet", icon: "pen-line", price: "$300 – $800" },
        { id: "e-tb-11", name: "Graphic Tablet", icon: "palette", price: "$200 – $2K" },
        { id: "e-tb-12", name: "Senior Tablet", icon: "users", price: "$150 – $400" },
        { id: "e-tb-13", name: "Dual-Screen", icon: "monitor", price: "$500 – $1.5K" },
      ]},
      { id: "cameras", label: "Cameras", icon: "camera", products: [
        { id: "e-cm-1", name: "DSLR Camera", icon: "camera", price: "$600 – $3K" },
        { id: "e-cm-2", name: "Mirrorless", icon: "aperture", price: "$800 – $4K" },
        { id: "e-cm-3", name: "Action Camera", icon: "mountain", price: "$200 – $500" },
        { id: "e-cm-4", name: "Instant Camera", icon: "image", price: "$70 – $200" },
        { id: "e-cm-5", name: "Cinema Camera", icon: "clapperboard", price: "$2K – $15K" },
        { id: "e-cm-6", name: "Webcam", icon: "webcam", price: "$50 – $300" },
        { id: "e-cm-7", name: "Trail Camera", icon: "tree", price: "$40 – $200" },
        { id: "e-cm-8", name: "Drone Camera", icon: "radio", price: "$300 – $2K" },
        { id: "e-cm-9", name: "Security Camera", icon: "cctv", price: "$30 – $500" },
      ]},
      { id: "audio", label: "Audio", icon: "headphones", products: [
        { id: "e-au-1", name: "Headphones", icon: "headphones", price: "$50 – $500" },
        { id: "e-au-2", name: "Speakers", icon: "speaker", price: "$80 – $1K" },
        { id: "e-au-3", name: "Earbuds", icon: "ear", price: "$30 – $300" },
        { id: "e-au-4", name: "Soundbar", icon: "tv", price: "$100 – $800" },
        { id: "e-au-5", name: "Studio Monitor", icon: "audio-lines", price: "$200 – $2K" },
        { id: "e-au-6", name: "Microphone", icon: "mic", price: "$50 – $500" },
        { id: "e-au-7", name: "Turntable", icon: "disc", price: "$100 – $1K" },
        { id: "e-au-8", name: "DAC / Amp", icon: "sliders-horizontal", price: "$50 – $800" },
        { id: "e-au-9", name: "Portable Speaker", icon: "volume-2", price: "$30 – $300" },
      ]},
      { id: "drones", label: "Drones", icon: "radio", products: [
        { id: "e-dr-1", name: "Photo Drone", icon: "camera", price: "$500 – $2K" },
        { id: "e-dr-2", name: "Racing Drone", icon: "gauge", price: "$200 – $800" },
        { id: "e-dr-3", name: "Mini Drone", icon: "star", price: "$50 – $300" },
        { id: "e-dr-4", name: "Commercial Drone", icon: "building", price: "$2K – $15K" },
        { id: "e-dr-5", name: "FPV Drone", icon: "glasses", price: "$300 – $1.2K" },
        { id: "e-dr-6", name: "Mapping Drone", icon: "map", price: "$3K – $20K" },
        { id: "e-dr-7", name: "Agricultural Drone", icon: "sprout", price: "$5K – $25K" },
        { id: "e-dr-8", name: "Underwater Drone", icon: "waves", price: "$1K – $8K" },
        { id: "e-dr-9", name: "Delivery Drone", icon: "package", price: "$5K – $30K" },
        { id: "e-dr-10", name: "Inspection Drone", icon: "scan-eye", price: "$2K – $15K" },
        { id: "e-dr-11", name: "Thermal Drone", icon: "thermometer", price: "$3K – $20K" },
        { id: "e-dr-12", name: "Selfie Drone", icon: "camera", price: "$100 – $500" },
        { id: "e-dr-13", name: "Lidar Drone", icon: "radar", price: "$8K – $40K" },
        { id: "e-dr-14", name: "Toy Drone", icon: "toy-brick", price: "$20 – $100" },
      ]},
      { id: "gaming", label: "Gaming", icon: "gamepad", products: [
        { id: "e-gm-1", name: "Game Console", icon: "gamepad", price: "$300 – $600" },
        { id: "e-gm-2", name: "VR Headset", icon: "glasses", price: "$300 – $1.5K" },
        { id: "e-gm-3", name: "Gaming Monitor", icon: "monitor", price: "$200 – $1K" },
        { id: "e-gm-4", name: "Handheld Console", icon: "smartphone", price: "$200 – $500" },
        { id: "e-gm-5", name: "Gaming Mouse", icon: "mouse", price: "$30 – $150" },
        { id: "e-gm-6", name: "Mech Keyboard", icon: "keyboard", price: "$50 – $300" },
        { id: "e-gm-7", name: "Gaming Chair", icon: "armchair", price: "$150 – $800" },
        { id: "e-gm-8", name: "Capture Card", icon: "tv", price: "$100 – $400" },
        { id: "e-gm-9", name: "Controller", icon: "joystick", price: "$30 – $200" },
      ]},
      { id: "accessories", label: "Accessories", icon: "watch", products: [
        { id: "e-ac-1", name: "Smartwatch", icon: "watch", price: "$150 – $800" },
        { id: "e-ac-2", name: "Chargers", icon: "battery-charging", price: "$15 – $80" },
        { id: "e-ac-3", name: "Cables", icon: "cable", price: "$5 – $40" },
        { id: "e-ac-4", name: "Cases & Covers", icon: "shield", price: "$10 – $60" },
        { id: "e-ac-5", name: "Power Bank", icon: "battery", price: "$20 – $100" },
        { id: "e-ac-6", name: "Screen Protector", icon: "square", price: "$5 – $30" },
        { id: "e-ac-7", name: "USB Hub", icon: "usb", price: "$15 – $80" },
        { id: "e-ac-8", name: "Memory Card", icon: "microchip", price: "$10 – $100" },
        { id: "e-ac-9", name: "Wireless Charger", icon: "zap", price: "$15 – $60" },
      ]},
    ],
  },

  // ── FURNITURE ──────────────────────────────────────────────────────────
  {
    id: "furniture",
    label: "Furniture",
    icon: "sofa",
    subcategories: [
      { id: "sofas", label: "Sofas", icon: "sofa", products: [
        { id: "f-sf-1", name: "Sectional Sofa", icon: "layers", price: "$800 – $4K" },
        { id: "f-sf-2", name: "Loveseat", icon: "heart", price: "$400 – $1.5K" },
        { id: "f-sf-3", name: "Recliner", icon: "armchair", price: "$300 – $2K" },
        { id: "f-sf-4", name: "Sleeper Sofa", icon: "bed", price: "$600 – $3K" },
        { id: "f-sf-5", name: "Chesterfield", icon: "crown", price: "$1K – $5K" },
        { id: "f-sf-6", name: "Futon", icon: "minimize", price: "$150 – $600" },
        { id: "f-sf-7", name: "Modular Sofa", icon: "blocks", price: "$800 – $5K" },
        { id: "f-sf-8", name: "Daybed", icon: "sun", price: "$300 – $1.5K" },
        { id: "f-sf-9", name: "Chaise Lounge", icon: "wind", price: "$400 – $2K" },
        { id: "f-sf-10", name: "Leather Sofa", icon: "layers", price: "$800 – $5K" },
        { id: "f-sf-11", name: "Corner Sofa", icon: "square", price: "$600 – $3K" },
        { id: "f-sf-12", name: "Outdoor Sofa", icon: "sun", price: "$400 – $2.5K" },
        { id: "f-sf-13", name: "Tufted Sofa", icon: "gem", price: "$700 – $4K" },
        { id: "f-sf-14", name: "Velvet Sofa", icon: "sparkles", price: "$600 – $3.5K" },
        { id: "f-sf-15", name: "Power Recliner", icon: "zap", price: "$500 – $3K" },
      ]},
      { id: "tables", label: "Tables", icon: "table", products: [
        { id: "f-tb-1", name: "Dining Table", icon: "users", price: "$300 – $3K" },
        { id: "f-tb-2", name: "Coffee Table", icon: "coffee", price: "$100 – $800" },
        { id: "f-tb-3", name: "Work Desk", icon: "monitor", price: "$200 – $1.5K" },
        { id: "f-tb-4", name: "Side Table", icon: "lamp", price: "$50 – $400" },
        { id: "f-tb-5", name: "Console Table", icon: "layers", price: "$100 – $600" },
        { id: "f-tb-6", name: "Dining Set", icon: "utensils", price: "$500 – $5K" },
        { id: "f-tb-7", name: "Folding Table", icon: "minimize", price: "$40 – $200" },
        { id: "f-tb-8", name: "Pub Table", icon: "beer", price: "$80 – $400" },
        { id: "f-tb-9", name: "Nesting Tables", icon: "boxes", price: "$60 – $300" },
      ]},
      { id: "chairs", label: "Chairs", icon: "armchair", products: [
        { id: "f-ch-1", name: "Office Chair", icon: "monitor", price: "$150 – $1.5K" },
        { id: "f-ch-2", name: "Dining Chair", icon: "utensils", price: "$50 – $500" },
        { id: "f-ch-3", name: "Accent Chair", icon: "sparkles", price: "$200 – $1K" },
        { id: "f-ch-4", name: "Bar Stool", icon: "beer", price: "$60 – $400" },
        { id: "f-ch-5", name: "Rocking Chair", icon: "rocking-chair", price: "$100 – $600" },
        { id: "f-ch-6", name: "Ergonomic Chair", icon: "heart", price: "$300 – $2K" },
        { id: "f-ch-7", name: "Folding Chair", icon: "minimize", price: "$20 – $100" },
        { id: "f-ch-8", name: "Bean Bag", icon: "circle", price: "$30 – $200" },
        { id: "f-ch-9", name: "Lounge Chair", icon: "sun", price: "$200 – $1.2K" },
      ]},
      { id: "beds", label: "Beds", icon: "bed", products: [
        { id: "f-bd-1", name: "King Bed", icon: "crown", price: "$500 – $4K" },
        { id: "f-bd-2", name: "Queen Bed", icon: "star", price: "$400 – $3K" },
        { id: "f-bd-3", name: "Bunk Bed", icon: "layers", price: "$300 – $1.5K" },
        { id: "f-bd-4", name: "Platform Bed", icon: "square", price: "$250 – $2K" },
        { id: "f-bd-5", name: "Murphy Bed", icon: "minimize", price: "$500 – $3K" },
        { id: "f-bd-6", name: "Toddler Bed", icon: "baby", price: "$80 – $300" },
        { id: "f-bd-7", name: "Adjustable Bed", icon: "sliders-horizontal", price: "$600 – $4K" },
        { id: "f-bd-8", name: "Canopy Bed", icon: "tent", price: "$400 – $3K" },
        { id: "f-bd-9", name: "Storage Bed", icon: "archive", price: "$350 – $2.5K" },
      ]},
      { id: "storage", label: "Storage", icon: "archive", products: [
        { id: "f-st-1", name: "Bookshelf", icon: "book-open", price: "$80 – $600" },
        { id: "f-st-2", name: "Wardrobe", icon: "shirt", price: "$200 – $2K" },
        { id: "f-st-3", name: "Cabinet", icon: "door-closed", price: "$150 – $1K" },
        { id: "f-st-4", name: "Chest of Drawers", icon: "box", price: "$120 – $800" },
        { id: "f-st-5", name: "Shoe Rack", icon: "footprints", price: "$20 – $150" },
        { id: "f-st-6", name: "TV Stand", icon: "tv", price: "$80 – $600" },
        { id: "f-st-7", name: "Curio Cabinet", icon: "gem", price: "$200 – $1.5K" },
        { id: "f-st-8", name: "Storage Ottoman", icon: "square", price: "$40 – $300" },
      ]},
      { id: "outdoor", label: "Outdoor", icon: "umbrella", products: [
        { id: "f-ot-1", name: "Patio Set", icon: "sun", price: "$300 – $3K" },
        { id: "f-ot-2", name: "Hammock", icon: "wind", price: "$40 – $300" },
        { id: "f-ot-3", name: "Garden Bench", icon: "tree", price: "$100 – $600" },
        { id: "f-ot-4", name: "Patio Umbrella", icon: "umbrella", price: "$50 – $400" },
        { id: "f-ot-5", name: "Outdoor Sofa", icon: "sofa", price: "$400 – $2K" },
        { id: "f-ot-6", name: "Fire Pit Table", icon: "flame", price: "$200 – $1.5K" },
        { id: "f-ot-7", name: "Swing Chair", icon: "wind", price: "$80 – $500" },
        { id: "f-ot-8", name: "Adirondack Chair", icon: "tree-pine", price: "$60 – $300" },
        { id: "f-ot-9", name: "Gazebo", icon: "home", price: "$500 – $5K" },
      ]},
      { id: "office-furn", label: "Office", icon: "desk", products: [
        { id: "f-of-1", name: "Standing Desk", icon: "zap", price: "$300 – $1.5K" },
        { id: "f-of-2", name: "Filing Cabinet", icon: "folder", price: "$80 – $400" },
        { id: "f-of-3", name: "Whiteboard", icon: "square", price: "$30 – $300" },
        { id: "f-of-4", name: "Desk Organizer", icon: "package", price: "$15 – $80" },
        { id: "f-of-5", name: "Bookcase", icon: "book-open", price: "$80 – $500" },
        { id: "f-of-6", name: "Conference Table", icon: "users", price: "$500 – $5K" },
        { id: "f-of-7", name: "Monitor Arm", icon: "monitor", price: "$30 – $200" },
        { id: "f-of-8", name: "Desk Mat", icon: "mouse", price: "$15 – $60" },
      ]},
      { id: "lighting", label: "Lighting", icon: "lamp", products: [
        { id: "f-lt-1", name: "Pendant Light", icon: "circle", price: "$40 – $500" },
        { id: "f-lt-2", name: "Floor Lamp", icon: "lamp-floor", price: "$50 – $400" },
        { id: "f-lt-3", name: "Table Lamp", icon: "lamp-desk", price: "$25 – $200" },
        { id: "f-lt-4", name: "Chandelier", icon: "sparkles", price: "$100 – $2K" },
        { id: "f-lt-5", name: "Wall Sconce", icon: "sun", price: "$30 – $200" },
        { id: "f-lt-6", name: "LED Strips", icon: "zap", price: "$10 – $60" },
        { id: "f-lt-7", name: "Track Lighting", icon: "target", price: "$40 – $300" },
        { id: "f-lt-8", name: "Desk Lamp", icon: "lamp", price: "$20 – $150" },
        { id: "f-lt-9", name: "Smart Bulbs", icon: "lightbulb", price: "$10 – $50/pack" },
      ]},
    ],
  },

  // ── ENERGY ─────────────────────────────────────────────────────────────
  {
    id: "energy",
    label: "Energy",
    icon: "sun",
    subcategories: [
      { id: "solar-panels", label: "Solar Panels", icon: "sun", products: [
        { id: "en-sp-1", name: "Residential Panel", icon: "home", price: "$200 – $500/panel" },
        { id: "en-sp-2", name: "Commercial Panel", icon: "building", price: "$300 – $800/panel" },
        { id: "en-sp-3", name: "Portable Panel", icon: "briefcase", price: "$100 – $400" },
        { id: "en-sp-4", name: "Roof-Mount Kit", icon: "layers", price: "$2K – $10K" },
        { id: "en-sp-5", name: "Thin-Film Panel", icon: "feather", price: "$150 – $400/panel" },
        { id: "en-sp-6", name: "Bifacial Panel", icon: "flip-horizontal", price: "$250 – $600/panel" },
        { id: "en-sp-7", name: "Solar Tiles", icon: "square", price: "$500 – $2K/sqm" },
        { id: "en-sp-8", name: "Tracking Mount", icon: "compass", price: "$1K – $5K" },
        { id: "en-sp-9", name: "Solar Carport", icon: "car", price: "$5K – $20K" },
      ]},
      { id: "batteries", label: "Batteries", icon: "battery", products: [
        { id: "en-bt-1", name: "Lithium Battery", icon: "zap", price: "$200 – $1K" },
        { id: "en-bt-2", name: "Lead-Acid", icon: "shield", price: "$80 – $400" },
        { id: "en-bt-3", name: "Home Battery", icon: "home", price: "$5K – $15K" },
        { id: "en-bt-4", name: "Industrial Cell", icon: "factory", price: "$1K – $10K" },
        { id: "en-bt-5", name: "Flow Battery", icon: "droplet", price: "$3K – $20K" },
        { id: "en-bt-6", name: "Solid-State Cell", icon: "atom", price: "$500 – $5K" },
        { id: "en-bt-7", name: "Portable Power", icon: "briefcase", price: "$100 – $800" },
        { id: "en-bt-8", name: "Nickel-MH", icon: "leaf", price: "$50 – $300" },
        { id: "en-bt-9", name: "Battery BMS", icon: "circuit-board", price: "$100 – $1K" },
      ]},
      { id: "inverters", label: "Inverters", icon: "zap", products: [
        { id: "en-iv-1", name: "String Inverter", icon: "link", price: "$800 – $3K" },
        { id: "en-iv-2", name: "Micro Inverter", icon: "microchip", price: "$150 – $400" },
        { id: "en-iv-3", name: "Hybrid Inverter", icon: "leaf", price: "$1K – $4K" },
        { id: "en-iv-4", name: "Off-Grid", icon: "mountain", price: "$1.5K – $5K" },
        { id: "en-iv-5", name: "Three-Phase", icon: "zap", price: "$2K – $8K" },
        { id: "en-iv-6", name: "Grid-Tie", icon: "plug", price: "$600 – $2.5K" },
        { id: "en-iv-7", name: "Power Optimizer", icon: "gauge", price: "$100 – $300" },
        { id: "en-iv-8", name: "Charger Inverter", icon: "battery-charging", price: "$500 – $2K" },
      ]},
      { id: "wind", label: "Wind Power", icon: "wind", products: [
        { id: "en-wp-1", name: "Wind Turbine", icon: "fan", price: "$5K – $50K" },
        { id: "en-wp-2", name: "Micro Wind", icon: "feather", price: "$500 – $3K" },
        { id: "en-wp-3", name: "Vertical Axis", icon: "circle", price: "$2K – $15K" },
        { id: "en-wp-4", name: "Residential Kit", icon: "home", price: "$3K – $20K" },
        { id: "en-wp-5", name: "Offshore Turbine", icon: "anchor", price: "$500K – $5M" },
        { id: "en-wp-6", name: "Hybrid Wind-Solar", icon: "sun", price: "$5K – $30K" },
        { id: "en-wp-7", name: "Wind Monitor", icon: "gauge", price: "$200 – $2K" },
        { id: "en-wp-8", name: "Tower Kit", icon: "layers", price: "$1K – $10K" },
        { id: "en-wp-9", name: "Bladeless Turbine", icon: "circle", price: "$3K – $15K" },
        { id: "en-wp-10", name: "Rooftop Wind", icon: "home", price: "$1K – $8K" },
        { id: "en-wp-11", name: "Wind Controller", icon: "cpu", price: "$300 – $3K" },
        { id: "en-wp-12", name: "Marine Turbine", icon: "anchor", price: "$50K – $500K" },
        { id: "en-wp-13", name: "Wind Farm Kit", icon: "building", price: "$100K – $1M" },
      ]},
      { id: "generators", label: "Generators", icon: "power", products: [
        { id: "en-gn-1", name: "Diesel Generator", icon: "fuel", price: "$2K – $20K" },
        { id: "en-gn-2", name: "Gas Generator", icon: "flame", price: "$500 – $5K" },
        { id: "en-gn-3", name: "Portable Unit", icon: "briefcase", price: "$300 – $2K" },
        { id: "en-gn-4", name: "Standby System", icon: "shield", price: "$5K – $30K" },
        { id: "en-gn-5", name: "Inverter Generator", icon: "cpu", price: "$500 – $3K" },
        { id: "en-gn-6", name: "Dual-Fuel Gen", icon: "leaf", price: "$600 – $4K" },
        { id: "en-gn-7", name: "Solar Generator", icon: "sun", price: "$200 – $2K" },
        { id: "en-gn-8", name: "Industrial Gen", icon: "factory", price: "$10K – $100K" },
        { id: "en-gn-9", name: "Marine Generator", icon: "anchor", price: "$3K – $25K" },
        { id: "en-gn-10", name: "Propane Generator", icon: "flame", price: "$400 – $4K" },
        { id: "en-gn-11", name: "Hydrogen Gen", icon: "atom", price: "$5K – $50K" },
        { id: "en-gn-12", name: "Transfer Switch", icon: "toggle-left", price: "$200 – $2K" },
        { id: "en-gn-13", name: "RV Generator", icon: "truck", price: "$500 – $5K" },
      ]},
      { id: "ev-chargers", label: "EV Chargers", icon: "plug", products: [
        { id: "en-ev-1", name: "Home Charger", icon: "home", price: "$400 – $1.5K" },
        { id: "en-ev-2", name: "Fast Charger", icon: "zap", price: "$10K – $50K" },
        { id: "en-ev-3", name: "Charging Station", icon: "map-pin", price: "$20K – $100K" },
        { id: "en-ev-4", name: "Portable Charger", icon: "briefcase", price: "$200 – $600" },
        { id: "en-ev-5", name: "Level 2 Charger", icon: "plug", price: "$500 – $2K" },
        { id: "en-ev-6", name: "Solar EV Charger", icon: "sun", price: "$2K – $8K" },
        { id: "en-ev-7", name: "Fleet Charger", icon: "truck", price: "$15K – $80K" },
        { id: "en-ev-8", name: "Wireless Charger", icon: "wifi", price: "$1K – $5K" },
        { id: "en-ev-9", name: "Smart Charger", icon: "cpu", price: "$600 – $3K" },
      ]},
    ],
  },

  // ── APPAREL ────────────────────────────────────────────────────────────
  {
    id: "apparel",
    label: "Apparel",
    icon: "shirt",
    subcategories: [
      { id: "mens", label: "Men's Wear", icon: "shirt", products: [
        { id: "a-mn-1", name: "Shirts", icon: "shirt", price: "$20 – $120" },
        { id: "a-mn-2", name: "Suits", icon: "briefcase", price: "$150 – $1.5K" },
        { id: "a-mn-3", name: "Jeans", icon: "layers", price: "$30 – $200" },
        { id: "a-mn-4", name: "Jackets", icon: "wind", price: "$50 – $500" },
        { id: "a-mn-5", name: "Polo Shirts", icon: "shirt", price: "$25 – $100" },
        { id: "a-mn-6", name: "Trousers", icon: "ruler", price: "$30 – $150" },
        { id: "a-mn-7", name: "Hoodies", icon: "cloud", price: "$30 – $120" },
        { id: "a-mn-8", name: "Shorts", icon: "sun", price: "$20 – $80" },
        { id: "a-mn-9", name: "Overcoats", icon: "shield", price: "$80 – $600" },
        { id: "a-mn-10", name: "Sweaters", icon: "cloud", price: "$25 – $150" },
        { id: "a-mn-11", name: "Tank Tops", icon: "sun", price: "$10 – $40" },
        { id: "a-mn-12", name: "Vests", icon: "layers", price: "$30 – $120" },
        { id: "a-mn-13", name: "Cargo Pants", icon: "package", price: "$25 – $100" },
        { id: "a-mn-14", name: "Linen Shirts", icon: "feather", price: "$30 – $120" },
        { id: "a-mn-15", name: "Leather Jackets", icon: "shield", price: "$100 – $800" },
      ]},
      { id: "womens", label: "Women's Wear", icon: "shirt", products: [
        { id: "a-wn-1", name: "Dresses", icon: "sparkles", price: "$30 – $300" },
        { id: "a-wn-2", name: "Blouses", icon: "shirt", price: "$20 – $150" },
        { id: "a-wn-3", name: "Skirts", icon: "flower", price: "$25 – $180" },
        { id: "a-wn-4", name: "Coats", icon: "wind", price: "$60 – $600" },
        { id: "a-wn-5", name: "Jumpsuits", icon: "star", price: "$40 – $200" },
        { id: "a-wn-6", name: "Cardigans", icon: "leaf", price: "$25 – $120" },
        { id: "a-wn-7", name: "Leggings", icon: "dumbbell", price: "$15 – $80" },
        { id: "a-wn-8", name: "Blazers", icon: "briefcase", price: "$50 – $300" },
        { id: "a-wn-9", name: "Maxi Dress", icon: "sun", price: "$35 – $250" },
        { id: "a-wn-10", name: "Crop Tops", icon: "scissors", price: "$15 – $60" },
        { id: "a-wn-11", name: "Wrap Dresses", icon: "ribbon", price: "$30 – $200" },
        { id: "a-wn-12", name: "Trench Coats", icon: "wind", price: "$60 – $500" },
        { id: "a-wn-13", name: "Palazzo Pants", icon: "ruler", price: "$25 – $120" },
        { id: "a-wn-14", name: "Rompers", icon: "sparkles", price: "$25 – $150" },
        { id: "a-wn-15", name: "Knitwear", icon: "cloud", price: "$30 – $180" },
      ]},
      { id: "kids", label: "Kids", icon: "baby", products: [
        { id: "a-kd-1", name: "Onesies", icon: "baby", price: "$10 – $40" },
        { id: "a-kd-2", name: "T-Shirts", icon: "shirt", price: "$8 – $30" },
        { id: "a-kd-3", name: "School Wear", icon: "graduation-cap", price: "$15 – $60" },
        { id: "a-kd-4", name: "Play Wear", icon: "toy-brick", price: "$12 – $45" },
        { id: "a-kd-5", name: "Winter Jackets", icon: "snowflake", price: "$25 – $100" },
        { id: "a-kd-6", name: "Rain Gear", icon: "cloud-rain", price: "$15 – $60" },
        { id: "a-kd-7", name: "Pajamas", icon: "moon", price: "$10 – $35" },
        { id: "a-kd-8", name: "Swimwear", icon: "waves", price: "$10 – $40" },
        { id: "a-kd-9", name: "Hoodies", icon: "cloud", price: "$15 – $50" },
        { id: "a-kd-10", name: "Costumes", icon: "star", price: "$15 – $60" },
        { id: "a-kd-11", name: "Sports Wear", icon: "dumbbell", price: "$12 – $45" },
        { id: "a-kd-12", name: "Formal Wear", icon: "gem", price: "$20 – $80" },
        { id: "a-kd-13", name: "Shoes", icon: "footprints", price: "$15 – $60" },
        { id: "a-kd-14", name: "Accessories", icon: "backpack", price: "$8 – $35" },
      ]},
      { id: "shoes", label: "Shoes", icon: "footprints", products: [
        { id: "a-sh-1", name: "Sneakers", icon: "footprints", price: "$40 – $250" },
        { id: "a-sh-2", name: "Boots", icon: "mountain", price: "$60 – $400" },
        { id: "a-sh-3", name: "Heels", icon: "sparkles", price: "$30 – $500" },
        { id: "a-sh-4", name: "Sandals", icon: "sun", price: "$15 – $120" },
        { id: "a-sh-5", name: "Loafers", icon: "briefcase", price: "$40 – $200" },
        { id: "a-sh-6", name: "Running Shoes", icon: "gauge", price: "$60 – $250" },
        { id: "a-sh-7", name: "Slides", icon: "feather", price: "$10 – $60" },
        { id: "a-sh-8", name: "Dress Shoes", icon: "gem", price: "$50 – $400" },
        { id: "a-sh-9", name: "Hiking Boots", icon: "mountain", price: "$70 – $300" },
      ]},
      { id: "bags", label: "Bags", icon: "briefcase", products: [
        { id: "a-bg-1", name: "Backpack", icon: "backpack", price: "$30 – $200" },
        { id: "a-bg-2", name: "Handbag", icon: "shopping-bag", price: "$40 – $500" },
        { id: "a-bg-3", name: "Duffle Bag", icon: "dumbbell", price: "$35 – $180" },
        { id: "a-bg-4", name: "Travel Bag", icon: "luggage", price: "$60 – $400" },
        { id: "a-bg-5", name: "Crossbody", icon: "link", price: "$25 – $200" },
        { id: "a-bg-6", name: "Tote Bag", icon: "shopping-bag", price: "$20 – $150" },
        { id: "a-bg-7", name: "Laptop Bag", icon: "laptop", price: "$30 – $200" },
        { id: "a-bg-8", name: "Clutch", icon: "gem", price: "$20 – $300" },
        { id: "a-bg-9", name: "Messenger Bag", icon: "briefcase", price: "$35 – $180" },
      ]},
      { id: "sportswear", label: "Sportswear", icon: "dumbbell", products: [
        { id: "a-sw-1", name: "Activewear", icon: "biceps-flexed", price: "$25 – $120" },
        { id: "a-sw-2", name: "Yoga Wear", icon: "heart", price: "$20 – $100" },
        { id: "a-sw-3", name: "Running Gear", icon: "footprints", price: "$30 – $150" },
        { id: "a-sw-4", name: "Swimwear", icon: "waves", price: "$20 – $100" },
        { id: "a-sw-5", name: "Gym Shorts", icon: "dumbbell", price: "$15 – $60" },
        { id: "a-sw-6", name: "Compression Wear", icon: "shield", price: "$25 – $80" },
        { id: "a-sw-7", name: "Sports Bras", icon: "heart", price: "$15 – $60" },
        { id: "a-sw-8", name: "Track Suits", icon: "layers", price: "$40 – $200" },
        { id: "a-sw-9", name: "Cycling Gear", icon: "gauge", price: "$30 – $200" },
        { id: "a-sw-10", name: "Ski Wear", icon: "snowflake", price: "$50 – $400" },
        { id: "a-sw-11", name: "Tennis Wear", icon: "target", price: "$25 – $120" },
        { id: "a-sw-12", name: "Golf Wear", icon: "flag", price: "$30 – $200" },
        { id: "a-sw-13", name: "Basketball Gear", icon: "circle", price: "$20 – $100" },
        { id: "a-sw-14", name: "Hiking Wear", icon: "mountain", price: "$30 – $180" },
      ]},
      { id: "formal", label: "Formal", icon: "glasses", products: [
        { id: "a-fm-1", name: "Tuxedos", icon: "star", price: "$200 – $2K" },
        { id: "a-fm-2", name: "Evening Gowns", icon: "sparkles", price: "$150 – $1.5K" },
        { id: "a-fm-3", name: "Dress Shoes", icon: "gem", price: "$80 – $600" },
        { id: "a-fm-4", name: "Ties & Bowties", icon: "ribbon", price: "$15 – $80" },
        { id: "a-fm-5", name: "Cufflinks", icon: "gem", price: "$20 – $200" },
        { id: "a-fm-6", name: "Pocket Squares", icon: "square", price: "$10 – $50" },
        { id: "a-fm-7", name: "Waistcoats", icon: "shirt", price: "$40 – $200" },
        { id: "a-fm-8", name: "Formal Belts", icon: "link", price: "$20 – $150" },
        { id: "a-fm-9", name: "Suspenders", icon: "layers", price: "$15 – $60" },
        { id: "a-fm-10", name: "Dress Shirts", icon: "shirt", price: "$30 – $200" },
        { id: "a-fm-11", name: "Formal Watches", icon: "watch", price: "$100 – $5K" },
        { id: "a-fm-12", name: "Top Hats", icon: "crown", price: "$30 – $200" },
        { id: "a-fm-13", name: "Wedding Suits", icon: "heart", price: "$200 – $3K" },
        { id: "a-fm-14", name: "Cocktail Dresses", icon: "sparkles", price: "$80 – $600" },
      ]},
      { id: "accessories-app", label: "Accessories", icon: "watch", products: [
        { id: "a-ac-1", name: "Watches", icon: "watch", price: "$50 – $5K" },
        { id: "a-ac-2", name: "Belts", icon: "link", price: "$15 – $150" },
        { id: "a-ac-3", name: "Sunglasses", icon: "glasses", price: "$20 – $400" },
        { id: "a-ac-4", name: "Jewelry", icon: "gem", price: "$25 – $2K" },
        { id: "a-ac-5", name: "Scarves", icon: "wind", price: "$15 – $150" },
        { id: "a-ac-6", name: "Hats & Caps", icon: "crown", price: "$10 – $80" },
        { id: "a-ac-7", name: "Wallets", icon: "wallet", price: "$20 – $200" },
        { id: "a-ac-8", name: "Gloves", icon: "hand", price: "$10 – $100" },
        { id: "a-ac-9", name: "Hair Accessories", icon: "sparkles", price: "$5 – $50" },
      ]},
      // ── Textiles (moved from standalone category into Apparel) ──
      { id: "fabrics", label: "Fabrics", icon: "square", products: [
        { id: "t-fb-1", name: "Cotton Fabric", icon: "cloud", price: "$3 – $20/yd" },
        { id: "t-fb-2", name: "Polyester", icon: "zap", price: "$2 – $15/yd" },
        { id: "t-fb-3", name: "Wool Fabric", icon: "circle", price: "$10 – $50/yd" },
        { id: "t-fb-4", name: "Nylon", icon: "shield", price: "$4 – $18/yd" },
        { id: "t-fb-5", name: "Chiffon", icon: "wind", price: "$5 – $25/yd" },
        { id: "t-fb-6", name: "Velvet", icon: "gem", price: "$8 – $35/yd" },
        { id: "t-fb-7", name: "Canvas", icon: "square", price: "$4 – $15/yd" },
        { id: "t-fb-8", name: "Jersey Knit", icon: "layers", price: "$3 – $12/yd" },
        { id: "t-fb-9", name: "Organza", icon: "sparkles", price: "$6 – $30/yd" },
      ]},
      { id: "yarn", label: "Yarn", icon: "circle", products: [
        { id: "t-yr-1", name: "Cotton Yarn", icon: "cloud", price: "$5 – $25/skein" },
        { id: "t-yr-2", name: "Acrylic Yarn", icon: "sparkles", price: "$3 – $15/skein" },
        { id: "t-yr-3", name: "Wool Yarn", icon: "circle", price: "$8 – $40/skein" },
        { id: "t-yr-4", name: "Silk Yarn", icon: "wind", price: "$15 – $60/skein" },
        { id: "t-yr-5", name: "Bamboo Yarn", icon: "sprout", price: "$6 – $25/skein" },
        { id: "t-yr-6", name: "Cashmere Yarn", icon: "crown", price: "$20 – $80/skein" },
        { id: "t-yr-7", name: "Mohair Yarn", icon: "feather", price: "$10 – $45/skein" },
        { id: "t-yr-8", name: "Blended Yarn", icon: "layers", price: "$5 – $20/skein" },
      ]},
      { id: "leather", label: "Leather", icon: "layers", products: [
        { id: "t-lt-1", name: "Full Grain", icon: "shield", price: "$8 – $30/sqft" },
        { id: "t-lt-2", name: "Suede", icon: "hand", price: "$5 – $20/sqft" },
        { id: "t-lt-3", name: "Bonded Leather", icon: "link", price: "$3 – $12/sqft" },
        { id: "t-lt-4", name: "Faux Leather", icon: "leaf", price: "$2 – $10/sqft" },
        { id: "t-lt-5", name: "Nubuck", icon: "feather", price: "$8 – $25/sqft" },
        { id: "t-lt-6", name: "Patent Leather", icon: "sparkles", price: "$6 – $22/sqft" },
        { id: "t-lt-7", name: "Tooling Leather", icon: "pen-tool", price: "$7 – $28/sqft" },
        { id: "t-lt-8", name: "Exotic Leather", icon: "gem", price: "$20 – $100/sqft" },
        { id: "t-lt-9", name: "Leather Dye", icon: "palette", price: "$5 – $20" },
      ]},
      { id: "silk", label: "Silk", icon: "wind", products: [
        { id: "t-sk-1", name: "Mulberry Silk", icon: "sparkles", price: "$20 – $80/yd" },
        { id: "t-sk-2", name: "Raw Silk", icon: "layers", price: "$15 – $50/yd" },
        { id: "t-sk-3", name: "Silk Blend", icon: "wind", price: "$10 – $35/yd" },
        { id: "t-sk-4", name: "Charmeuse", icon: "gem", price: "$18 – $60/yd" },
        { id: "t-sk-5", name: "Dupioni Silk", icon: "star", price: "$12 – $45/yd" },
        { id: "t-sk-6", name: "Silk Satin", icon: "crown", price: "$15 – $55/yd" },
        { id: "t-sk-7", name: "Habotai Silk", icon: "feather", price: "$10 – $30/yd" },
        { id: "t-sk-8", name: "Silk Chiffon", icon: "cloud", price: "$12 – $40/yd" },
      ]},
      { id: "denim", label: "Denim", icon: "shirt", products: [
        { id: "t-dn-1", name: "Raw Denim", icon: "square", price: "$8 – $30/yd" },
        { id: "t-dn-2", name: "Stretch Denim", icon: "zap", price: "$6 – $25/yd" },
        { id: "t-dn-3", name: "Selvedge Denim", icon: "ruler", price: "$15 – $50/yd" },
        { id: "t-dn-4", name: "Organic Denim", icon: "leaf", price: "$10 – $35/yd" },
        { id: "t-dn-5", name: "Washed Denim", icon: "droplet", price: "$6 – $22/yd" },
        { id: "t-dn-6", name: "Bull Denim", icon: "shield", price: "$5 – $18/yd" },
        { id: "t-dn-7", name: "Chambray", icon: "wind", price: "$4 – $15/yd" },
        { id: "t-dn-8", name: "Black Denim", icon: "circle", price: "$7 – $28/yd" },
      ]},
      { id: "linen", label: "Linen", icon: "square", products: [
        { id: "t-ln-1", name: "Pure Linen", icon: "square", price: "$10 – $40/yd" },
        { id: "t-ln-2", name: "Linen Blend", icon: "layers", price: "$6 – $25/yd" },
        { id: "t-ln-3", name: "Washed Linen", icon: "droplet", price: "$12 – $45/yd" },
        { id: "t-ln-4", name: "Belgian Linen", icon: "star", price: "$20 – $60/yd" },
        { id: "t-ln-5", name: "Linen Canvas", icon: "shield", price: "$8 – $30/yd" },
        { id: "t-ln-6", name: "Handkerchief Linen", icon: "feather", price: "$10 – $35/yd" },
        { id: "t-ln-7", name: "Linen Burlap", icon: "square", price: "$3 – $12/yd" },
        { id: "t-ln-8", name: "Irish Linen", icon: "crown", price: "$25 – $70/yd" },
      ]},
    ],
  },

  // ── BEAUTY ─────────────────────────────────────────────────────────────
  {
    id: "beauty",
    label: "Beauty",
    icon: "sparkles",
    subcategories: [
      { id: "skincare", label: "Skincare", icon: "droplet", products: [
        { id: "b-sk-1", name: "Moisturizer", icon: "droplet", price: "$10 – $80" },
        { id: "b-sk-2", name: "Serum", icon: "test-tube", price: "$15 – $120" },
        { id: "b-sk-3", name: "Cleanser", icon: "sparkles", price: "$8 – $50" },
        { id: "b-sk-4", name: "Sunscreen", icon: "sun", price: "$10 – $40" },
        { id: "b-sk-5", name: "Toner", icon: "droplets", price: "$8 – $35" },
        { id: "b-sk-6", name: "Eye Cream", icon: "eye", price: "$15 – $80" },
        { id: "b-sk-7", name: "Face Mask", icon: "smile", price: "$5 – $30" },
        { id: "b-sk-8", name: "Exfoliator", icon: "rotate-ccw", price: "$10 – $45" },
        { id: "b-sk-9", name: "Retinol Cream", icon: "star", price: "$20 – $100" },
      ]},
      { id: "makeup", label: "Makeup", icon: "palette", products: [
        { id: "b-mk-1", name: "Foundation", icon: "palette", price: "$15 – $60" },
        { id: "b-mk-2", name: "Lipstick", icon: "heart", price: "$8 – $40" },
        { id: "b-mk-3", name: "Mascara", icon: "eye", price: "$8 – $35" },
        { id: "b-mk-4", name: "Blush", icon: "flower", price: "$10 – $45" },
        { id: "b-mk-5", name: "Concealer", icon: "droplet", price: "$8 – $35" },
        { id: "b-mk-6", name: "Eyeshadow Palette", icon: "swatch-book", price: "$15 – $60" },
        { id: "b-mk-7", name: "Setting Spray", icon: "spray-can", price: "$8 – $30" },
        { id: "b-mk-8", name: "Eyeliner", icon: "pen-line", price: "$5 – $25" },
        { id: "b-mk-9", name: "Bronzer", icon: "sun", price: "$10 – $40" },
      ]},
      { id: "haircare", label: "Haircare", icon: "scissors", products: [
        { id: "b-hc-1", name: "Shampoo", icon: "droplet", price: "$8 – $40" },
        { id: "b-hc-2", name: "Conditioner", icon: "heart", price: "$8 – $40" },
        { id: "b-hc-3", name: "Hair Oil", icon: "flask", price: "$10 – $50" },
        { id: "b-hc-4", name: "Styling Tools", icon: "wind", price: "$20 – $200" },
        { id: "b-hc-5", name: "Hair Mask", icon: "sparkles", price: "$10 – $40" },
        { id: "b-hc-6", name: "Dry Shampoo", icon: "spray-can", price: "$8 – $25" },
        { id: "b-hc-7", name: "Hair Color", icon: "palette", price: "$8 – $30" },
        { id: "b-hc-8", name: "Leave-In Spray", icon: "droplets", price: "$8 – $35" },
        { id: "b-hc-9", name: "Scalp Treatment", icon: "leaf", price: "$12 – $50" },
      ]},
      { id: "fragrance", label: "Fragrance", icon: "flower", products: [
        { id: "b-fr-1", name: "Perfume", icon: "sparkles", price: "$30 – $300" },
        { id: "b-fr-2", name: "Cologne", icon: "droplet", price: "$25 – $200" },
        { id: "b-fr-3", name: "Body Mist", icon: "spray-can", price: "$10 – $40" },
        { id: "b-fr-4", name: "Essential Oil", icon: "flask", price: "$8 – $50" },
        { id: "b-fr-5", name: "Roll-On Perfume", icon: "circle", price: "$10 – $30" },
        { id: "b-fr-6", name: "Scented Candle", icon: "flame", price: "$10 – $60" },
        { id: "b-fr-7", name: "Room Spray", icon: "wind", price: "$8 – $30" },
        { id: "b-fr-8", name: "Incense", icon: "cloud", price: "$5 – $25" },
        { id: "b-fr-9", name: "Diffuser", icon: "flower-2", price: "$15 – $80" },
      ]},
      { id: "nails", label: "Nails", icon: "gem", products: [
        { id: "b-nl-1", name: "Nail Polish", icon: "palette", price: "$5 – $20" },
        { id: "b-nl-2", name: "Gel Kit", icon: "gem", price: "$20 – $80" },
        { id: "b-nl-3", name: "Nail Art", icon: "sparkles", price: "$10 – $40" },
        { id: "b-nl-4", name: "Care Kit", icon: "heart", price: "$8 – $30" },
        { id: "b-nl-5", name: "Press-On Nails", icon: "star", price: "$5 – $25" },
        { id: "b-nl-6", name: "UV Lamp", icon: "lightbulb", price: "$15 – $60" },
        { id: "b-nl-7", name: "Cuticle Oil", icon: "droplet", price: "$5 – $15" },
        { id: "b-nl-8", name: "Nail Stickers", icon: "sticker", price: "$3 – $12" },
        { id: "b-nl-9", name: "Nail Drills", icon: "drill", price: "$20 – $100" },
        { id: "b-nl-10", name: "Base & Top Coat", icon: "layers", price: "$5 – $20" },
        { id: "b-nl-11", name: "Acrylic Powder", icon: "sparkles", price: "$10 – $40" },
        { id: "b-nl-12", name: "Nail Forms", icon: "square", price: "$5 – $15" },
        { id: "b-nl-13", name: "Dipping Powder", icon: "palette", price: "$12 – $45" },
      ]},
      { id: "wellness", label: "Wellness", icon: "heart", products: [
        { id: "b-wl-1", name: "Vitamins", icon: "pill", price: "$10 – $50" },
        { id: "b-wl-2", name: "Supplements", icon: "pill-bottle", price: "$15 – $60" },
        { id: "b-wl-3", name: "Aromatherapy", icon: "flower", price: "$10 – $40" },
        { id: "b-wl-4", name: "Massage Tools", icon: "hand", price: "$15 – $100" },
        { id: "b-wl-5", name: "Jade Roller", icon: "gem", price: "$10 – $40" },
        { id: "b-wl-6", name: "Bath Salts", icon: "bath", price: "$8 – $30" },
        { id: "b-wl-7", name: "Sleep Aids", icon: "moon", price: "$10 – $50" },
        { id: "b-wl-8", name: "Yoga Mat", icon: "heart-pulse", price: "$15 – $80" },
        { id: "b-wl-9", name: "Meditation App", icon: "brain", price: "$5 – $15/mo" },
      ]},
    ],
  },

  // ── MINING ─────────────────────────────────────────────────────────────
  {
    id: "mining",
    label: "Mining",
    icon: "pickaxe",
    subcategories: [
      { id: "minerals", label: "Minerals", icon: "gem", products: [
        { id: "m-mn-1", name: "Quartz", icon: "gem", price: "$50 – $500/ton" },
        { id: "m-mn-2", name: "Limestone", icon: "mountain", price: "$20 – $80/ton" },
        { id: "m-mn-3", name: "Gypsum", icon: "layers", price: "$30 – $100/ton" },
        { id: "m-mn-4", name: "Feldspar", icon: "hexagon", price: "$40 – $150/ton" },
        { id: "m-mn-5", name: "Mica", icon: "sparkles", price: "$100 – $1K/ton" },
        { id: "m-mn-6", name: "Barite", icon: "weight", price: "$60 – $200/ton" },
        { id: "m-mn-7", name: "Dolomite", icon: "triangle", price: "$25 – $90/ton" },
        { id: "m-mn-8", name: "Silica Sand", icon: "circle", price: "$15 – $60/ton" },
        { id: "m-mn-9", name: "Talc", icon: "feather", price: "$80 – $400/ton" },
      ]},
      { id: "metals", label: "Metals", icon: "layers", products: [
        { id: "m-mt-1", name: "Gold Ore", icon: "star", price: "$1K – $50K/ton" },
        { id: "m-mt-2", name: "Iron Ore", icon: "shield", price: "$50 – $200/ton" },
        { id: "m-mt-3", name: "Copper Ore", icon: "cable", price: "$200 – $800/ton" },
        { id: "m-mt-4", name: "Silver Ore", icon: "circle", price: "$500 – $5K/ton" },
        { id: "m-mt-5", name: "Platinum Ore", icon: "gem", price: "$2K – $30K/ton" },
        { id: "m-mt-6", name: "Lithium", icon: "battery", price: "$5K – $40K/ton" },
        { id: "m-mt-7", name: "Zinc Ore", icon: "layers", price: "$100 – $500/ton" },
        { id: "m-mt-8", name: "Cobalt Ore", icon: "atom", price: "$1K – $10K/ton" },
        { id: "m-mt-9", name: "Tin Ore", icon: "cylinder", price: "$300 – $2K/ton" },
      ]},
      { id: "excavation", label: "Excavation", icon: "shovel", products: [
        { id: "m-ex-1", name: "Excavator", icon: "shovel", price: "$80K – $500K" },
        { id: "m-ex-2", name: "Bucket Loader", icon: "box", price: "$60K – $300K" },
        { id: "m-ex-3", name: "Dragline", icon: "anchor", price: "$500K – $5M" },
        { id: "m-ex-4", name: "Tunneling Rig", icon: "mountain", price: "$200K – $2M" },
        { id: "m-ex-5", name: "Haul Truck", icon: "truck", price: "$100K – $1M" },
        { id: "m-ex-6", name: "Scraper", icon: "layers", price: "$80K – $400K" },
        { id: "m-ex-7", name: "Dredger", icon: "waves", price: "$200K – $3M" },
        { id: "m-ex-8", name: "Trencher", icon: "ruler", price: "$50K – $300K" },
      ]},
      { id: "drilling", label: "Drilling", icon: "drill", products: [
        { id: "m-dr-1", name: "Drill Bits", icon: "target", price: "$100 – $5K" },
        { id: "m-dr-2", name: "Core Sampler", icon: "cylinder", price: "$500 – $10K" },
        { id: "m-dr-3", name: "Pneumatic Drill", icon: "wind", price: "$1K – $20K" },
        { id: "m-dr-4", name: "Rotary Drill", icon: "rotate-cw", price: "$50K – $500K" },
        { id: "m-dr-5", name: "Diamond Drill", icon: "diamond", price: "$2K – $30K" },
        { id: "m-dr-6", name: "DTH Hammer", icon: "hammer", price: "$1K – $15K" },
        { id: "m-dr-7", name: "Drill Rods", icon: "ruler", price: "$200 – $3K" },
        { id: "m-dr-8", name: "Mud Pumps", icon: "droplets", price: "$5K – $50K" },
      ]},
      { id: "processing", label: "Processing", icon: "cog", products: [
        { id: "m-pr-1", name: "Crusher", icon: "hammer", price: "$10K – $200K" },
        { id: "m-pr-2", name: "Ball Mill", icon: "circle", price: "$20K – $300K" },
        { id: "m-pr-3", name: "Flotation Cell", icon: "waves", price: "$15K – $150K" },
        { id: "m-pr-4", name: "Screening Machine", icon: "filter", price: "$8K – $100K" },
        { id: "m-pr-5", name: "Magnetic Separator", icon: "magnet", price: "$5K – $80K" },
        { id: "m-pr-6", name: "Centrifuge", icon: "rotate-cw", price: "$10K – $100K" },
        { id: "m-pr-7", name: "Thickener", icon: "droplet", price: "$20K – $200K" },
        { id: "m-pr-8", name: "Leaching Tank", icon: "flask", price: "$15K – $120K" },
        { id: "m-pr-9", name: "Conveyor System", icon: "move-horizontal", price: "$5K – $50K" },
      ]},
      { id: "safety-mining", label: "Safety", icon: "shield", products: [
        { id: "m-sf-1", name: "Gas Detector", icon: "radar", price: "$200 – $2K" },
        { id: "m-sf-2", name: "Rescue Kit", icon: "cross", price: "$500 – $3K" },
        { id: "m-sf-3", name: "Ventilation Fan", icon: "fan", price: "$1K – $10K" },
        { id: "m-sf-4", name: "Headlamp", icon: "flashlight", price: "$30 – $200" },
        { id: "m-sf-5", name: "Self-Rescuer", icon: "life-buoy", price: "$200 – $800" },
        { id: "m-sf-6", name: "Dust Suppressor", icon: "spray-can", price: "$500 – $5K" },
        { id: "m-sf-7", name: "Fire Extinguisher", icon: "fire-extinguisher", price: "$30 – $200" },
        { id: "m-sf-8", name: "Communication Radio", icon: "antenna", price: "$100 – $800" },
        { id: "m-sf-9", name: "PPE Bundle", icon: "hard-hat", price: "$150 – $500" },
      ]},
    ],
  },

  // ── AGRICULTURE ────────────────────────────────────────────────────────
  {
    id: "agriculture",
    label: "Agriculture",
    icon: "wheat",
    subcategories: [
      { id: "grains", label: "Grains", icon: "wheat", products: [
        { id: "ag-gr-1", name: "Wheat", icon: "wheat", price: "$200 – $400/ton" },
        { id: "ag-gr-2", name: "Rice", icon: "leaf", price: "$300 – $600/ton" },
        { id: "ag-gr-3", name: "Corn", icon: "sun", price: "$150 – $350/ton" },
        { id: "ag-gr-4", name: "Oats", icon: "sprout", price: "$180 – $400/ton" },
        { id: "ag-gr-5", name: "Barley", icon: "wheat", price: "$160 – $350/ton" },
        { id: "ag-gr-6", name: "Millet", icon: "circle", price: "$200 – $500/ton" },
        { id: "ag-gr-7", name: "Sorghum", icon: "sun", price: "$150 – $300/ton" },
        { id: "ag-gr-8", name: "Quinoa", icon: "star", price: "$1K – $3K/ton" },
        { id: "ag-gr-9", name: "Rye", icon: "leaf", price: "$170 – $380/ton" },
      ]},
      { id: "fruits", label: "Fruits", icon: "apple", products: [
        { id: "ag-fr-1", name: "Oranges", icon: "citrus", price: "$400 – $1.2K/ton" },
        { id: "ag-fr-2", name: "Lemons", icon: "citrus", price: "$500 – $1.5K/ton" },
        { id: "ag-fr-3", name: "Limes", icon: "citrus", price: "$600 – $1.8K/ton" },
        { id: "ag-fr-4", name: "Grapefruits", icon: "citrus", price: "$350 – $1K/ton" },
        { id: "ag-fr-5", name: "Tangerines", icon: "citrus", price: "$500 – $1.5K/ton" },
        { id: "ag-fr-6", name: "Mangoes", icon: "tree-palm", price: "$800 – $3K/ton" },
        { id: "ag-fr-7", name: "Pineapples", icon: "tree-palm", price: "$400 – $1.5K/ton" },
        { id: "ag-fr-8", name: "Papayas", icon: "tree-palm", price: "$300 – $1.2K/ton" },
        { id: "ag-fr-9", name: "Passion Fruit", icon: "flower", price: "$2K – $6K/ton" },
        { id: "ag-fr-10", name: "Dragon Fruit", icon: "sparkles", price: "$1.5K – $5K/ton" },
        { id: "ag-fr-11", name: "Strawberries", icon: "cherry", price: "$2K – $8K/ton" },
        { id: "ag-fr-12", name: "Blueberries", icon: "cherry", price: "$3K – $10K/ton" },
        { id: "ag-fr-13", name: "Raspberries", icon: "cherry", price: "$4K – $12K/ton" },
        { id: "ag-fr-14", name: "Blackberries", icon: "cherry", price: "$3K – $10K/ton" },
        { id: "ag-fr-15", name: "Cranberries", icon: "cherry", price: "$1.5K – $5K/ton" },
        { id: "ag-fr-16", name: "Peaches", icon: "apple", price: "$600 – $2K/ton" },
        { id: "ag-fr-17", name: "Plums", icon: "apple", price: "$500 – $1.8K/ton" },
        { id: "ag-fr-18", name: "Cherries", icon: "cherry", price: "$2K – $8K/ton" },
        { id: "ag-fr-19", name: "Apricots", icon: "apple", price: "$700 – $2.5K/ton" },
        { id: "ag-fr-20", name: "Nectarines", icon: "apple", price: "$600 – $2K/ton" },
        { id: "ag-fr-21", name: "Grapes", icon: "grape", price: "$500 – $3K/ton" },
        { id: "ag-fr-22", name: "Bananas", icon: "banana", price: "$300 – $800/ton" },
        { id: "ag-fr-23", name: "Apples", icon: "apple", price: "$400 – $1.5K/ton" },
        { id: "ag-fr-24", name: "Pears", icon: "apple", price: "$450 – $1.5K/ton" },
        { id: "ag-fr-25", name: "Avocados", icon: "leaf", price: "$1K – $4K/ton" },
        { id: "ag-fr-26", name: "Watermelons", icon: "circle", price: "$150 – $500/ton" },
        { id: "ag-fr-27", name: "Cantaloupes", icon: "circle", price: "$200 – $700/ton" },
        { id: "ag-fr-28", name: "Honeydew Melon", icon: "circle", price: "$200 – $800/ton" },
        { id: "ag-fr-29", name: "Pomegranates", icon: "gem", price: "$1K – $4K/ton" },
        { id: "ag-fr-30", name: "Figs", icon: "leaf", price: "$2K – $8K/ton" },
        { id: "ag-fr-31", name: "Dates", icon: "tree-palm", price: "$1.5K – $6K/ton" },
        { id: "ag-fr-32", name: "Coconuts", icon: "tree-palm", price: "$300 – $1K/ton" },
        { id: "ag-fr-33", name: "Guavas", icon: "leaf", price: "$600 – $2K/ton" },
        { id: "ag-fr-34", name: "Lychees", icon: "sparkles", price: "$2K – $8K/ton" },
        { id: "ag-fr-35", name: "Kiwi Fruit", icon: "leaf", price: "$1K – $3.5K/ton" },
        { id: "ag-fr-36", name: "Persimmons", icon: "sun", price: "$800 – $3K/ton" },
        { id: "ag-fr-37", name: "Jackfruit", icon: "tree-palm", price: "$400 – $1.5K/ton" },
        { id: "ag-fr-38", name: "Durian", icon: "shield", price: "$2K – $10K/ton" },
        { id: "ag-fr-39", name: "Star Fruit", icon: "star", price: "$1K – $4K/ton" },
        { id: "ag-fr-40", name: "Plantains", icon: "banana", price: "$200 – $600/ton" },
      ]},
      { id: "vegetables", label: "Vegetables", icon: "carrot", products: [
        { id: "ag-vg-1", name: "Carrots", icon: "carrot", price: "$200 – $600/ton" },
        { id: "ag-vg-2", name: "Potatoes", icon: "circle", price: "$150 – $500/ton" },
        { id: "ag-vg-3", name: "Sweet Potatoes", icon: "circle", price: "$200 – $700/ton" },
        { id: "ag-vg-4", name: "Beets", icon: "circle", price: "$300 – $900/ton" },
        { id: "ag-vg-5", name: "Turnips", icon: "circle", price: "$200 – $600/ton" },
        { id: "ag-vg-6", name: "Radishes", icon: "circle", price: "$300 – $800/ton" },
        { id: "ag-vg-7", name: "Spinach", icon: "leafy-green", price: "$800 – $3K/ton" },
        { id: "ag-vg-8", name: "Lettuce", icon: "leafy-green", price: "$500 – $2K/ton" },
        { id: "ag-vg-9", name: "Kale", icon: "leafy-green", price: "$800 – $3K/ton" },
        { id: "ag-vg-10", name: "Swiss Chard", icon: "leafy-green", price: "$700 – $2.5K/ton" },
        { id: "ag-vg-11", name: "Arugula", icon: "leaf", price: "$1K – $4K/ton" },
        { id: "ag-vg-12", name: "Cabbage", icon: "leafy-green", price: "$200 – $600/ton" },
        { id: "ag-vg-13", name: "Broccoli", icon: "tree", price: "$500 – $1.8K/ton" },
        { id: "ag-vg-14", name: "Cauliflower", icon: "cloud", price: "$400 – $1.5K/ton" },
        { id: "ag-vg-15", name: "Brussels Sprouts", icon: "sprout", price: "$600 – $2K/ton" },
        { id: "ag-vg-16", name: "Green Beans", icon: "bean", price: "$400 – $1.5K/ton" },
        { id: "ag-vg-17", name: "Peas", icon: "bean", price: "$500 – $1.8K/ton" },
        { id: "ag-vg-18", name: "Lentils", icon: "bean", price: "$600 – $2K/ton" },
        { id: "ag-vg-19", name: "Chickpeas", icon: "bean", price: "$500 – $1.5K/ton" },
        { id: "ag-vg-20", name: "Soybeans", icon: "bean", price: "$350 – $1K/ton" },
        { id: "ag-vg-21", name: "Tomatoes", icon: "apple", price: "$400 – $1.2K/ton" },
        { id: "ag-vg-22", name: "Bell Peppers", icon: "flame", price: "$500 – $2K/ton" },
        { id: "ag-vg-23", name: "Chili Peppers", icon: "flame", price: "$800 – $4K/ton" },
        { id: "ag-vg-24", name: "Jalapeños", icon: "flame", price: "$600 – $2.5K/ton" },
        { id: "ag-vg-25", name: "Onions", icon: "layers", price: "$200 – $600/ton" },
        { id: "ag-vg-26", name: "Garlic", icon: "layers", price: "$1K – $4K/ton" },
        { id: "ag-vg-27", name: "Shallots", icon: "layers", price: "$800 – $3K/ton" },
        { id: "ag-vg-28", name: "Leeks", icon: "layers", price: "$500 – $1.8K/ton" },
        { id: "ag-vg-29", name: "Cucumbers", icon: "leaf", price: "$300 – $1K/ton" },
        { id: "ag-vg-30", name: "Zucchini", icon: "leaf", price: "$300 – $1K/ton" },
        { id: "ag-vg-31", name: "Pumpkins", icon: "circle", price: "$200 – $800/ton" },
        { id: "ag-vg-32", name: "Butternut Squash", icon: "circle", price: "$250 – $900/ton" },
        { id: "ag-vg-33", name: "Eggplant", icon: "circle", price: "$400 – $1.5K/ton" },
        { id: "ag-vg-34", name: "Celery", icon: "leaf", price: "$400 – $1.2K/ton" },
        { id: "ag-vg-35", name: "Asparagus", icon: "sprout", price: "$2K – $8K/ton" },
        { id: "ag-vg-36", name: "Artichokes", icon: "flower", price: "$1.5K – $5K/ton" },
        { id: "ag-vg-37", name: "Mushrooms", icon: "umbrella", price: "$2K – $10K/ton" },
        { id: "ag-vg-38", name: "Corn on the Cob", icon: "sun", price: "$200 – $600/ton" },
        { id: "ag-vg-39", name: "Okra", icon: "sprout", price: "$500 – $2K/ton" },
        { id: "ag-vg-40", name: "Ginger", icon: "zap", price: "$1.5K – $6K/ton" },
        { id: "ag-vg-41", name: "Turmeric", icon: "sun", price: "$1K – $5K/ton" },
        { id: "ag-vg-42", name: "Basil", icon: "sprout", price: "$3K – $12K/ton" },
        { id: "ag-vg-43", name: "Cilantro", icon: "sprout", price: "$2K – $8K/ton" },
        { id: "ag-vg-44", name: "Parsley", icon: "sprout", price: "$2K – $8K/ton" },
        { id: "ag-vg-45", name: "Mint", icon: "sprout", price: "$3K – $10K/ton" },
      ]},
      { id: "seeds", label: "Seeds", icon: "sprout", products: [
        { id: "ag-sd-1", name: "Vegetable Seeds", icon: "sprout", price: "$5 – $50/kg" },
        { id: "ag-sd-2", name: "Flower Seeds", icon: "flower", price: "$10 – $80/kg" },
        { id: "ag-sd-3", name: "Tree Seeds", icon: "tree", price: "$15 – $100/kg" },
        { id: "ag-sd-4", name: "Organic Seeds", icon: "leaf", price: "$8 – $60/kg" },
        { id: "ag-sd-5", name: "Grass Seeds", icon: "sprout", price: "$3 – $20/kg" },
        { id: "ag-sd-6", name: "Herb Seeds", icon: "leaf", price: "$5 – $40/kg" },
        { id: "ag-sd-7", name: "Hybrid Seeds", icon: "zap", price: "$10 – $80/kg" },
        { id: "ag-sd-8", name: "Cover Crop Seeds", icon: "shield", price: "$4 – $25/kg" },
      ]},
      { id: "fertilizer", label: "Fertilizer", icon: "flask", products: [
        { id: "ag-ft-1", name: "Nitrogen Mix", icon: "flask", price: "$200 – $600/ton" },
        { id: "ag-ft-2", name: "Organic Compost", icon: "leaf", price: "$50 – $300/ton" },
        { id: "ag-ft-3", name: "Phosphate", icon: "layers", price: "$300 – $800/ton" },
        { id: "ag-ft-4", name: "Potash", icon: "gem", price: "$250 – $700/ton" },
        { id: "ag-ft-5", name: "Urea", icon: "circle", price: "$250 – $600/ton" },
        { id: "ag-ft-6", name: "Micronutrients", icon: "atom", price: "$500 – $2K/ton" },
        { id: "ag-ft-7", name: "Liquid Fertilizer", icon: "droplet", price: "$100 – $500/ton" },
        { id: "ag-ft-8", name: "Slow Release", icon: "timer", price: "$300 – $800/ton" },
        { id: "ag-ft-9", name: "Biofertilizer", icon: "sprout", price: "$150 – $600/ton" },
      ]},
      { id: "farm-equip", label: "Equipment", icon: "tractor", products: [
        { id: "ag-eq-1", name: "Tractor", icon: "tractor", price: "$20K – $200K" },
        { id: "ag-eq-2", name: "Harvester", icon: "wheat", price: "$50K – $500K" },
        { id: "ag-eq-3", name: "Irrigation System", icon: "droplets", price: "$2K – $20K" },
        { id: "ag-eq-4", name: "Seeder", icon: "sprout", price: "$5K – $50K" },
        { id: "ag-eq-5", name: "Plow", icon: "shovel", price: "$2K – $15K" },
        { id: "ag-eq-6", name: "Sprayer", icon: "spray-can", price: "$1K – $20K" },
        { id: "ag-eq-7", name: "Baler", icon: "box", price: "$10K – $80K" },
        { id: "ag-eq-8", name: "Grain Dryer", icon: "thermometer", price: "$5K – $50K" },
        { id: "ag-eq-9", name: "Greenhouse Kit", icon: "home", price: "$2K – $30K" },
      ]},
      { id: "livestock", label: "Livestock", icon: "beef", products: [
        { id: "ag-ls-1", name: "Cattle", icon: "beef", price: "$1K – $5K/head" },
        { id: "ag-ls-2", name: "Poultry", icon: "bird", price: "$5 – $30/bird" },
        { id: "ag-ls-3", name: "Sheep", icon: "cloud", price: "$200 – $800/head" },
        { id: "ag-ls-4", name: "Fish Stock", icon: "fish", price: "$2 – $20/kg" },
        { id: "ag-ls-5", name: "Goats", icon: "mountain", price: "$150 – $600/head" },
        { id: "ag-ls-6", name: "Pigs", icon: "piggy-bank", price: "$100 – $500/head" },
        { id: "ag-ls-7", name: "Horses", icon: "wind", price: "$2K – $50K/head" },
        { id: "ag-ls-8", name: "Bees & Hives", icon: "hexagon", price: "$100 – $500/hive" },
        { id: "ag-ls-9", name: "Feed & Hay", icon: "wheat", price: "$100 – $300/ton" },
      ]},
      { id: "dairy", label: "Dairy", icon: "milk", products: [
        { id: "ag-dy-1", name: "Fresh Milk", icon: "milk", price: "$0.5 – $2/L" },
        { id: "ag-dy-2", name: "Cheese", icon: "circle", price: "$5 – $50/kg" },
        { id: "ag-dy-3", name: "Cream", icon: "droplet", price: "$2 – $10/L" },
        { id: "ag-dy-4", name: "Butter", icon: "square", price: "$3 – $15/kg" },
        { id: "ag-dy-5", name: "Yogurt", icon: "cup-soda", price: "$2 – $8/kg" },
        { id: "ag-dy-6", name: "Ghee", icon: "star", price: "$5 – $20/kg" },
        { id: "ag-dy-7", name: "Whey Protein", icon: "biceps-flexed", price: "$10 – $40/kg" },
        { id: "ag-dy-8", name: "Powdered Milk", icon: "cloud", price: "$3 – $12/kg" },
        { id: "ag-dy-9", name: "Ice Cream Mix", icon: "ice-cream-cone", price: "$4 – $15/kg" },
      ]},
    ],
  },

  // ── SPORTS & ACCESSORIES ────────────────────────────────────────────────
  {
    id: "sports",
    label: "Sports",
    icon: "basketball",
    subcategories: [
      { id: "team-sports", label: "Team Sports", icon: "circle", products: [
        { id: "s-ts-1", name: "Basketballs", icon: "circle", price: "$20 – $200" },
        { id: "s-ts-2", name: "Soccer Balls", icon: "circle", price: "$15 – $180" },
        { id: "s-ts-3", name: "Footballs", icon: "target", price: "$20 – $150" },
        { id: "s-ts-4", name: "Volleyball", icon: "circle", price: "$15 – $100" },
        { id: "s-ts-5", name: "Baseball Bats", icon: "bolt", price: "$30 – $400" },
        { id: "s-ts-6", name: "Hockey Sticks", icon: "flag", price: "$40 – $300" },
        { id: "s-ts-7", name: "Cricket Gear", icon: "shield", price: "$25 – $500" },
        { id: "s-ts-8", name: "Rugby Balls", icon: "circle", price: "$20 – $120" },
        { id: "s-ts-9", name: "Team Jerseys", icon: "shirt", price: "$25 – $150" },
      ]},
      { id: "fitness", label: "Fitness", icon: "dumbbell", products: [
        { id: "s-ft-1", name: "Dumbbells", icon: "dumbbell", price: "$15 – $200" },
        { id: "s-ft-2", name: "Kettlebells", icon: "weight", price: "$20 – $150" },
        { id: "s-ft-3", name: "Resistance Bands", icon: "link", price: "$8 – $40" },
        { id: "s-ft-4", name: "Yoga Mats", icon: "heart", price: "$15 – $100" },
        { id: "s-ft-5", name: "Treadmills", icon: "gauge", price: "$300 – $5K" },
        { id: "s-ft-6", name: "Spin Bikes", icon: "gauge", price: "$200 – $3K" },
        { id: "s-ft-7", name: "Rowing Machines", icon: "waves", price: "$300 – $2.5K" },
        { id: "s-ft-8", name: "Pull-Up Bars", icon: "biceps-flexed", price: "$20 – $100" },
        { id: "s-ft-9", name: "Jump Ropes", icon: "zap", price: "$5 – $30" },
      ]},
      { id: "outdoor-sports", label: "Outdoor", icon: "mountain", products: [
        { id: "s-od-1", name: "Hiking Poles", icon: "mountain", price: "$20 – $150" },
        { id: "s-od-2", name: "Climbing Gear", icon: "anchor", price: "$40 – $500" },
        { id: "s-od-3", name: "Camping Tents", icon: "tent", price: "$50 – $800" },
        { id: "s-od-4", name: "Kayaks", icon: "waves", price: "$200 – $3K" },
        { id: "s-od-5", name: "Fishing Rods", icon: "fish", price: "$20 – $500" },
        { id: "s-od-6", name: "Binoculars", icon: "eye", price: "$30 – $600" },
        { id: "s-od-7", name: "Sleeping Bags", icon: "moon", price: "$25 – $300" },
        { id: "s-od-8", name: "Backpacks", icon: "backpack", price: "$30 – $250" },
        { id: "s-od-9", name: "Surfboards", icon: "waves", price: "$100 – $1.5K" },
      ]},
      { id: "racket-sports", label: "Racket Sports", icon: "target", products: [
        { id: "s-rs-1", name: "Tennis Rackets", icon: "target", price: "$30 – $300" },
        { id: "s-rs-2", name: "Badminton Sets", icon: "feather", price: "$15 – $200" },
        { id: "s-rs-3", name: "Table Tennis", icon: "circle", price: "$10 – $150" },
        { id: "s-rs-4", name: "Squash Rackets", icon: "target", price: "$30 – $250" },
        { id: "s-rs-5", name: "Tennis Balls", icon: "circle", price: "$5 – $30" },
        { id: "s-rs-6", name: "Shuttlecocks", icon: "feather", price: "$5 – $25" },
        { id: "s-rs-7", name: "Racket Bags", icon: "briefcase", price: "$20 – $100" },
        { id: "s-rs-8", name: "Grip Tape", icon: "link", price: "$3 – $15" },
      ]},
      { id: "winter-sports", label: "Winter Sports", icon: "snowflake", products: [
        { id: "s-ws-1", name: "Skis", icon: "mountain", price: "$200 – $1.5K" },
        { id: "s-ws-2", name: "Snowboards", icon: "wind", price: "$150 – $800" },
        { id: "s-ws-3", name: "Ski Boots", icon: "footprints", price: "$100 – $600" },
        { id: "s-ws-4", name: "Snow Goggles", icon: "glasses", price: "$30 – $300" },
        { id: "s-ws-5", name: "Ice Skates", icon: "snowflake", price: "$40 – $500" },
        { id: "s-ws-6", name: "Ski Poles", icon: "bolt", price: "$20 – $150" },
        { id: "s-ws-7", name: "Snow Helmets", icon: "shield", price: "$40 – $250" },
        { id: "s-ws-8", name: "Thermal Layers", icon: "thermometer", price: "$20 – $100" },
      ]},
      { id: "cycling", label: "Cycling", icon: "gauge", products: [
        { id: "s-cy-1", name: "Road Bikes", icon: "gauge", price: "$300 – $10K" },
        { id: "s-cy-2", name: "Mountain Bikes", icon: "mountain", price: "$400 – $8K" },
        { id: "s-cy-3", name: "E-Bikes", icon: "zap", price: "$800 – $6K" },
        { id: "s-cy-4", name: "Bike Helmets", icon: "shield", price: "$25 – $300" },
        { id: "s-cy-5", name: "Cycling Shoes", icon: "footprints", price: "$50 – $400" },
        { id: "s-cy-6", name: "Bike Locks", icon: "link", price: "$10 – $100" },
        { id: "s-cy-7", name: "Cycling Jerseys", icon: "shirt", price: "$25 – $200" },
        { id: "s-cy-8", name: "Bike Lights", icon: "flashlight", price: "$10 – $80" },
        { id: "s-cy-9", name: "Water Bottles", icon: "cup-soda", price: "$5 – $30" },
      ]},
      { id: "water-sports", label: "Water Sports", icon: "waves", products: [
        { id: "s-wt-1", name: "Swim Goggles", icon: "glasses", price: "$10 – $80" },
        { id: "s-wt-2", name: "Wetsuits", icon: "shield", price: "$50 – $500" },
        { id: "s-wt-3", name: "Paddleboards", icon: "waves", price: "$200 – $1.5K" },
        { id: "s-wt-4", name: "Snorkel Sets", icon: "eye", price: "$20 – $150" },
        { id: "s-wt-5", name: "Life Jackets", icon: "life-buoy", price: "$20 – $200" },
        { id: "s-wt-6", name: "Diving Gear", icon: "anchor", price: "$100 – $2K" },
        { id: "s-wt-7", name: "Water Shoes", icon: "footprints", price: "$15 – $80" },
        { id: "s-wt-8", name: "Pool Floats", icon: "sun", price: "$10 – $60" },
      ]},
      { id: "sports-accessories", label: "Accessories", icon: "watch", products: [
        { id: "s-ac-1", name: "Sports Watches", icon: "watch", price: "$30 – $800" },
        { id: "s-ac-2", name: "Fitness Trackers", icon: "heart-pulse", price: "$30 – $400" },
        { id: "s-ac-3", name: "Sports Bags", icon: "briefcase", price: "$20 – $200" },
        { id: "s-ac-4", name: "Sweatbands", icon: "ribbon", price: "$5 – $20" },
        { id: "s-ac-5", name: "Sports Glasses", icon: "glasses", price: "$15 – $250" },
        { id: "s-ac-6", name: "Knee Braces", icon: "shield", price: "$10 – $80" },
        { id: "s-ac-7", name: "Grip Gloves", icon: "hand", price: "$10 – $60" },
        { id: "s-ac-8", name: "Compression Socks", icon: "footprints", price: "$8 – $40" },
        { id: "s-ac-9", name: "Hydration Packs", icon: "droplet", price: "$20 – $100" },
      ]},
    ],
  },
];

// Trending products for search dropdown
export const trendingProducts = [
  { id: "1", name: "mini drone 3 DJI", icon: "radio", category: "electronics" },
  { id: "2", name: "wheat France", icon: "wheat", category: "agriculture" },
  { id: "3", name: "F-150 Ford pickup truck", icon: "truck", category: "vehicles" },
  { id: "4", name: "solar panel 400W", icon: "sun", category: "energy" },
  { id: "5", name: "leather briefcase", icon: "briefcase", category: "apparel" },
  { id: "6", name: "industrial robot arm", icon: "bot", category: "industrial" },
  { id: "7", name: "oak dining table", icon: "utensils", category: "furniture" },
];

// All searchable items (categories + subcategories + products + trending)
export function getAllSearchableItems() {
  const items: { name: string; icon: string; category: string; subcategory?: string; productId?: string }[] = [];
  
  categories.forEach((cat) => {
    items.push({ name: cat.label, icon: cat.icon, category: cat.id });
    cat.subcategories.forEach((sub) => {
      items.push({ name: sub.label, icon: sub.icon, category: cat.id, subcategory: sub.id });
      sub.products.forEach((prod) => {
        items.push({ name: prod.name, icon: prod.icon, category: cat.id, subcategory: sub.id, productId: prod.id });
      });
    });
  });

  return items;
}
