import type { LucideIcon } from "lucide-react";
import {
  Car,
  Factory,
  Hammer,
  Monitor,
  Gamepad2,
  Sofa,
  Tent,
  Baby,
  Scissors,
  Cable,
  Hand,
  Sprout,
  Apple,
  Snowflake,
  Shirt,
  Palette,
  Wind,
  Gem,
  Wheat,
  Volleyball,
  Settings,
  Bike,
  Activity,
  Ship,
  Lightbulb,
  Plane,
  Truck,
  Wrench,
  Boxes,
  Package,
  Zap,
  Drill,
  HardHat,
  Cpu,
  Smartphone,
  Tablet,
  BedDouble,
  Table,
  Paintbrush,
  Armchair,
  BatteryCharging,
  PlugZap,
  Trees,
  Sun,
  Plug,
  Camera,
  Sparkles,
  Leaf,
  Tractor,
  Droplets,
  Pickaxe,
  Droplet,
  FlaskConical,
  PawPrint,
  Watch,
  Gauge,
  Footprints,
  Trophy,
  Dumbbell,
  LucideTicketsPlane,
  Wallet,
  WholeWord,
  Shield,
  Feather,
} from "lucide-react";

export type Subcategory = {
  name: string;
  nameZh?: string;
  icon: LucideIcon;
  items: string[];
  itemsZh?: string[];
  count: number;
};

export type Category = {
  id: string;
  name: string;
  nameZh?: string;
  icon: LucideIcon;
  accent: string;
  count: number;
  subcategories: Subcategory[];
};

export const categories: Category[] = [
  {
    id: "vehicles",
    name: "Vehicles",
    nameZh: "车辆",
    icon: Car,
    accent: "#3B82F6",
    count: 111,
    subcategories: [
      {
        name: "SUV",
        nameZh: "SUV/越野车",
        icon: Car,
        count: 18,
        items: [
          "Compact Crossover",
          "Family SUV",
          "Off-Road SUV",
          "Luxury SUV",
          "Hybrid SUV",
          "Electric SUV",
          "Subcompact SUV",
          "Performance SUV",
          "3-Row SUV",
          "Rugged SUV",
          "Diesel SUV",
          "Coupe SUV",
          "Armored SUV",
          "Adventure SUV"
        ],
        itemsZh: [
          "紧凑跨界",
          "家庭SUV",
          "越野SUV",
          "豪华SUV",
          "混动SUV",
          "电动SUV",
          "微型SUV",
          "高性能SUV",
          "三排SUV",
          "硬派SUV",
          "柴油SUV",
          "轿跑SUV",
          "装甲SUV",
          "冒险SUV"
        ]
      },
      {
        name: "Electric",
        nameZh: "电动车",
        icon: Zap,
        count: 22,
        items: [
          "Electric Sedan",
          "Electric SUV",
          "Electric Truck",
          "Luxury EV",
          "EV Hypercar",
          "Compact EV",
          "EV Van",
          "Sports EV",
          "Solar-Assisted EV",
          "Electric Bus"
        ],
        itemsZh: [
          "电动轿车",
          "电动SUV",
          "电动卡车",
          "豪华电车",
          "电动超级跑车",
          "紧凑型电动车",
          "电动厢式车",
          "电动跑车",
          "太阳能辅助电动车",
          "电动巴士"
        ]
      },
      {
        name: "Accessories",
        nameZh: "汽车配件",
        icon: Wrench,
        count: 10,
        items: [
          "Car Cover",
          "Dash Camera",
          "GPS Tracker",
          "Seat Cover",
          "Roof Rack",
          "Tow Bar",
          "Car Alarm",
          "Jump Starter",
          "Floor Mats",
          "Racing Helmet"
        ],
        itemsZh: [
          "车罩",
          "行车记录仪",
          "GPS追踪器",
          "座椅套",
          "车顶架",
          "拖车杆",
          "汽车警报器",
          "应急启动电源",
          "脚垫",
          "赛车头盔"
        ]
      },
      {
        name: "Heavy Vehicles",
        nameZh: "重型车辆",
        icon: Truck,
        count: 10,
        items: [
          "Forklift",
          "Dump Truck",
          "Cement Mixer",
          "Crane Truck",
          "Excavator",
          "Bulldozer",
          "Semi-Truck",
          "Garbage Truck",
          "Tanker Truck",
          "Fire Truck"
        ],
        itemsZh: [
          "叉车",
          "自卸卡车",
          "混凝土搅拌车",
          "起重卡车",
          "挖掘机",
          "推土机",
          "半挂卡车",
          "垃圾车",
          "油罐车",
          "消防车"
        ]
      },
      {
        name: "Bike",
        nameZh: "自行车",
        icon: Bike,
        count: 8,
        items: [
          "Mountain Bike",
          "Road Bike",
          "BMX Bike",
          "Gravel Bike",
          "City Bike",
          "Track Bike",
          "Folding Bike",
          "Cargo Bike"
        ],
        itemsZh: [
          "山地自行车",
          "公路自行车",
          "BMX自行车",
          "砾石自行车",
          "城市自行车",
          "场地自行车",
          "折叠自行车",
          "货运自行车"
        ]
      },
      {
        name: "E Bikes",
        nameZh: "电动自行车",
        icon: Zap,
        count: 8,
        items: [
          "Electric Scooter",
          "E-Mountain Bike",
          "E-City Bike",
          "Fat Tire E-Bike",
          "Folding E-Bike",
          "E-Cargo Bike",
          "Speed Pedelec",
          "E-Moped"
        ],
        itemsZh: [
          "电动滑板车",
          "电动山地车",
          "电动城市车",
          "胖胎电动自行车",
          "折叠电动自行车",
          "电动货运自行车",
          "高速助力自行车",
          "电动轻便摩托"
        ]
      },
      {
        name: "Ships",
        nameZh: "船舶",
        icon: Ship,
        count: 10,
        items: [
          "Yacht",
          "Speedboat",
          "Sailboat",
          "Cargo Ship",
          "Ferry",
          "Catamaran",
          "Fishing Boat",
          "Luxury Cruise",
          "Patrol Vessel",
          "Research Ship"
        ],
        itemsZh: [
          "游艇",
          "快艇",
          "帆船",
          "货船",
          "渡轮",
          "双体船",
          "渔船",
          "豪华邮轮",
          "巡逻船",
          "科考船"
        ]
      },
      {
        name: "Helicopters",
        nameZh: "直升机",
        icon: Plane,
        count: 8,
        items: [
          "Private Helicopter",
          "Executive Helicopter",
          "Medical Helicopter",
          "Military Helicopter",
          "Tour Helicopter",
          "Cargo Helicopter",
          "Sport Helicopter",
          "Training Helicopter"
        ],
        itemsZh: [
          "私人直升机",
          "商务直升机",
          "医疗直升机",
          "军用直升机",
          "观光直升机",
          "货运直升机",
          "运动直升机",
          "训练直升机"
        ]
      },
      {
        name: "Drones",
        nameZh: "无人机",
        icon: Plane,
        count: 9,
        items: [
          "Consumer Drone",
          "Professional Drone",
          "Racing Drone",
          "Agricultural Drone",
          "Delivery Drone",
          "Military Drone",
          "Inspection Drone",
          "FPV Drone",
          "Mapping Drone"
        ],
        itemsZh: [
          "消费级无人机",
          "专业无人机",
          "竞速无人机",
          "农业无人机",
          "配送无人机",
          "军用无人机",
          "巡检无人机",
          "第一视角无人机",
          "测绘无人机"
        ]
      },
      {
        name: "Auto Parts",
        nameZh: "汽车零部件",
        icon: Wrench,
        count: 12,
        items: [
          "Engine Parts",
          "Brake System",
          "Suspension",
          "Exhaust System",
          "Transmission",
          "Wheels & Tires",
          "Lighting",
          "Fuel System",
          "Electrical",
          "Body Parts",
          "Cooling System",
          "Interior Parts"
        ],
        itemsZh: [
          "发动机零件",
          "制动系统",
          "悬挂系统",
          "排气系统",
          "变速箱",
          "轮胎与车轮",
          "照明系统",
          "燃油系统",
          "电气系统",
          "车身部件",
          "冷却系统",
          "内饰部件"
        ]
      },
      {
        name: "Accessories",
        nameZh: "汽车配件",
        icon: Wrench,
        count: 10,
        items: [
          "Car Cover",
          "Dash Camera",
          "GPS Tracker",
          "Seat Cover",
          "Roof Rack",
          "Tow Bar",
          "Car Alarm",
          "Jump Starter",
          "Floor Mats",
          "Racing Helmet"
        ],
        itemsZh: [
          "车罩",
          "行车记录仪",
          "GPS追踪器",
          "座椅套",
          "车顶架",
          "拖车杆",
          "汽车警报器",
          "应急启动电源",
          "脚垫",
          "赛车头盔"
        ]
      },
    ],
  },
  {
    id: "industrial",
    name: "Industrial",
    nameZh: "工业设备",
    icon: Factory,
    accent: "#6366F1",
    count: 76,
    subcategories: [
      {
        name: "Industrial Machines",
        nameZh: "工业机械",
        icon: Settings,
        count: 15,
        items: [
          "CNC Machine",
          "Lathe",
          "Hydraulic Press",
          "Conveyor Belt",
          "Milling Machine",
          "Injection Molder",
          "Punch Press",
          "3D Printer Ind.",
          "Laser Cutter",
          "CNC Router",
          "Plasma Cutter",
          "Waterjet Cutter",
          "Bending Machine",
          "Grinding Machine",
          "EDM Machine"
        ],
        itemsZh: [
          "数控机床",
          "车床",
          "液压机",
          "传送带",
          "铣床",
          "注塑机",
          "冲压机",
          "工业3D打印机",
          "激光切割机",
          "CNC雕刻机",
          "等离子切割机",
          "水刀切割机",
          "折弯机",
          "磨床",
          "电火花机"
        ]
      },
      {
        name: "Raw Materials",
        nameZh: "原材料",
        icon: Boxes,
        count: 9,
        items: [
          "Steel Sheets",
          "Aluminum Bars",
          "Copper Wire",
          "Polymers",
          "Carbon Fiber",
          "Titanium Plate",
          "Brass Rods",
          "Stainless Steel",
          "Rubber Compound"
        ],
        itemsZh: [
          "钢板",
          "铝棒",
          "铜线",
          "聚合物",
          "碳纤维",
          "钛板",
          "黄铜棒",
          "不锈钢",
          "橡胶化合物"
        ]
      },
      {
        name: "Industrial Chemicals",
        nameZh: "工业化学品",
        icon: FlaskConical,
        count: 8,
        items: [
          "Industrial Solvents",
          "Adhesive Resin",
          "Coating Chemicals",
          "Industrial Acids",
          "Cleaning Agents",
          "Lubricants",
          "Catalysts",
          "Pigments & Dyes"
        ],
        itemsZh: [
          "工业溶剂",
          "胶黏树脂",
          "涂层化学品",
          "工业酸类",
          "清洁剂",
          "润滑剂",
          "催化剂",
          "颜料与染料"
        ]
      },
      {
        name: "Packaging",
        nameZh: "包装材料",
        icon: Package,
        count: 9,
        items: [
          "Corrugated Boxes",
          "Shrink Film",
          "Pallets",
          "Bubble Wrap",
          "Foam Inserts",
          "Tape & Strapping",
          "Crates & Bins",
          "Label Rolls",
          "Vacuum Bags"
        ],
        itemsZh: [
          "瓦楞纸箱",
          "收缩膜",
          "托盘",
          "气泡膜",
          "泡沫内衬",
          "胶带与捆扎带",
          "周转箱",
          "标签卷",
          "真空袋"
        ]
      },
      {
        name: "Safety Gear",
        nameZh: "安全防护装备",
        icon: HardHat,
        count: 9,
        items: [
          "Hard Hats",
          "Safety Goggles",
          "Safety Gloves",
          "Hi-Vis Vests",
          "Steel-Toe Boots",
          "Ear Protection",
          "Face Shields",
          "Respirators",
          "Fall Harness"
        ],
        itemsZh: [
          "安全头盔",
          "护目镜",
          "安全手套",
          "高可视背心",
          "钢头安全靴",
          "耳部防护",
          "面罩",
          "呼吸防护器",
          "防坠安全带"
        ]
      },
      {
        name: "Power Tools",
        nameZh: "电动工具",
        icon: Drill,
        count: 8,
        items: [
          "Drill Press",
          "Angle Grinder",
          "Welding Machine",
          "Air Compressor",
          "Plasma Cutter",
          "Band Saw",
          "Heat Gun",
          "Riveting Tool"
        ],
        itemsZh: [
          "台钻",
          "角磨机",
          "焊机",
          "空气压缩机",
          "等离子切割机",
          "带锯机",
          "热风枪",
          "铆接工具"
        ]
      },
      {
        name: "Construction Equipment",
        nameZh: "工程机械",
        icon: Factory,
        count: 9,
        items: [
          "Excavator",
          "Bulldozer",
          "Crane",
          "Forklift",
          "Backhoe Loader",
          "Dump Truck",
          "Concrete Mixer",
          "Road Roller",
          "Skid Steer"
        ],
        itemsZh: [
          "挖掘机",
          "推土机",
          "起重机",
          "叉车",
          "反铲装载机",
          "自卸卡车",
          "混凝土搅拌车",
          "压路机",
          "滑移装载机"
        ]
      },
      {
        name: "Factory Automation",
        nameZh: "工厂自动化",
        icon: Cpu,
        count: 9,
        items: [
          "Robotic Arm",
          "PLC Controller",
          "Sensor Array",
          "Vision System",
          "Motor Drives",
          "Conveyor System",
          "Pick & Place Bot",
          "AGV Robot",
          "SCADA System"
        ],
        itemsZh: [
          "机械臂",
          "PLC控制器",
          "传感器阵列",
          "视觉系统",
          "电机驱动器",
          "输送系统",
          "取放机器人",
          "AGV机器人",
          "SCADA系统"
        ]
      },],
  },
  {
    id: "hardware",
    name: "Hardware",
    nameZh: "五金工具",
    icon: Hammer,
    accent: "#F59E0B",
    count: 81,
    subcategories: [
      {
        name: "Hand Tools",
        nameZh: "手动工具",
        icon: Hammer,
        count: 12,
        items: [
          "Screwdriver Set",
          "Pliers",
          "Tape Measure",
          "Socket Set",
          "Wrenches",
          "Hammer Set",
          "Chisel Set",
          "Clamps",
          "Level Tool"
        ],
        itemsZh: [
          "螺丝刀套装",
          "钳子",
          "卷尺",
          "套筒工具组",
          "扳手",
          "锤子套装",
          "凿子套装",
          "夹具",
          "水平工具"]
      },
      {
        name: "Power Tools",
        nameZh: "电动工具",
        icon: Drill,
        count: 11,
        items: [
          "Cordless Drill",
          "Circular Saw",
          "Orbital Sander",
          "Jigsaw",
          "Impact Driver",
          "Router",
          "Reciprocating Saw",
          "Nail Gun",
          "Table Saw",
          "Drills",
          "Saws"
        ],
        itemsZh: [
          "无线电钻",
          "圆锯",
          "轨道砂光机",
          "曲线锯",
          "冲击起子",
          "修边机",
          "往复锯",
          "射钉枪",
          "台锯",
          "电钻",
          "电锯"
        ]
      },
      {
        name: "Fasteners",
        nameZh: "紧固件",
        icon: Wrench,
        count: 9,
        items: [
          "Bolts & Nuts",
          "Wood Screws",
          "Wall Anchors",
          "Nails",
          "Rivets",
          "Washers",
          "Toggle Bolts",
          "Concrete Screws"
        ],
        itemsZh: [
          "螺栓与螺母",
          "木螺钉",
          "墙体锚栓",
          "钉子",
          "铆钉",
          "垫圈",
          "蝴蝶螺栓",
          "混凝土螺钉"
        ]
      },
      {
        name: "Plumbing",
        nameZh: "管道用品",
        icon: Droplets,
        count: 9,
        items: [
          "Pipe Fittings",
          "Faucets",
          "Valves",
          "Water Heater",
          "Sump Pump",
          "Drain Pipes",
          "Toilet Parts",
          "Shower Heads",
          "Water Filters"
        ],
        itemsZh: [
          "管件",
          "水龙头",
          "阀门",
          "热水器",
          "排水泵",
          "排水管",
          "马桶配件",
          "淋浴喷头",
          "净水器"
        ]
      },
      {
        name: "Electrical",
        nameZh: "电气配件",
        icon: PlugZap,
        count: 14,
        items: [
          "Wire & Cable",
          "Switches",
          "Circuit Breakers",
          "Outlets",
          "Conduit",
          "Junction Boxes",
          "Light Fixtures",
          "Dimmer Switch",
          "Electrical Tape"
        ],
        itemsZh: [
          "电线与电缆",
          "开关",
          "断路器",
          "插座",
          "导管",
          "接线盒",
          "照明灯具",
          "调光开关",
          "电工胶带"
        ]
      },
      {
        name: "Paint & Finish",
        nameZh: "油漆与涂料",
        icon: Paintbrush,
        count: 9,
        items: [
          "Wall Paint",
          "Primer",
          "Wood Stain",
          "Spray Paint",
          "Varnish",
          "Epoxy Floor",
          "Texture Paint",
          "Paint Brushes",
          "Rollers & Trays"
        ],
        itemsZh: [
          "墙面漆",
          "底漆",
          "木器染色剂",
          "喷漆",
          "清漆",
          "环氧地坪漆",
          "纹理漆",
          "油漆刷",
          "滚筒与托盘"
        ]
      },
      {
        name: "Lumber",
        nameZh: "木材与板材",
        icon: Trees,
        count: 14,
        items: [
          "Plywood",
          "Hardwood",
          "MDF Board",
          "Timber Beams",
          "Pine Boards",
          "Cedar Planks",
          "OSB Sheets",
          "Bamboo Planks",
          "Walnut Boards",
          "Birch Plywood",
          "Teak Wood",
          "Reclaimed Wood",
          "Treated Lumber",
          "Moulding & Trim"
        ],
        itemsZh: [
          "胶合板",
          "硬木",
          "中密度纤维板",
          "木梁",
          "松木板",
          "雪松木板",
          "定向刨花板",
          "竹板",
          "胡桃木板",
          "桦木胶合板",
          "柚木",
          "再生木材",
          "防腐木",
          "装饰线条"
        ]
      },
      {
        name: "Adhesives",
        nameZh: "胶粘剂与密封剂",
        icon: Droplet,
        count: 14,
        items: [
          "Wood Glue",
          "Epoxy",
          "Sealant",
          "Mounting Tape",
          "Super Glue",
          "Contact Cement",
          "Spray Adhesive",
          "Caulk",
          "Hot Glue Gun",
          "Foam Tape",
          "Thread Locker",
          "Silicone Sealant",
          "Welding Adhesive",
          "Tile Adhesive"
        ],
        itemsZh: [
          "木工胶",
          "环氧树脂",
          "密封剂",
          "安装胶带",
          "强力胶",
          "万能胶",
          "喷胶",
          "填缝胶",
          "热熔胶枪",
          "泡棉胶带",
          "螺纹锁固剂",
          "硅胶密封剂",
          "焊接胶",
          "瓷砖胶"
        ]
      }
    ],
  },
  {
    id: "electronics",
    name: "Electronics",
    nameZh: "电子产品",
    icon: Monitor,
    accent: "#8B5CF6",
    count: 92,
    subcategories: [
      {
        name: "Laptops",
        nameZh: "笔记本电脑",
        icon: Monitor,
        count: 15,
        items: [
          "Gaming Laptop",
          "Business Laptop",
          "Ultrabook",
          "Workstation",
          "Chromebook",
          "2-in-1 Laptop",
          "Student Laptop",
          "Creative Pro",
          "Rugged Laptop",
          "Mini Laptop",
          "AI Laptop",
          "Fanless Laptop",
          "Linux Laptop",
          "Touch Laptop",
          "Refurbished Pro"
        ],
        itemsZh: [
          "游戏笔记本",
          "商务笔记本",
          "超极本",
          "工作站笔记本",
          "Chromebook笔记本",
          "二合一笔记本",
          "学生笔记本",
          "创意专业本",
          "加固型笔记本",
          "迷你笔记本",
          "AI笔记本",
          "无风扇笔记本",
          "Linux笔记本",
          "触控笔记本",
          "翻新专业本"
        ]
      },
      {
        name: "Phones",
        nameZh: "手机",
        icon: Smartphone,
        count: 14,
        items: [
          "Flagship Phone",
          "Budget Phone",
          "Rugged Phone",
          "Foldable Phone",
          "Camera Phone",
          "Gaming Phone",
          "Compact Phone",
          "5G Phone",
          "Senior Phone",
          "Business Phone",
          "Kids Phone",
          "Satellite Phone",
          "Dual-SIM Phone",
          "Refurbished Phone"
        ],
        itemsZh: [
          "旗舰手机",
          "经济型手机",
          "三防手机",
          "折叠手机",
          "拍照手机",
          "游戏手机",
          "小屏手机",
          "5G手机",
          "老人手机",
          "商务手机",
          "儿童手机",
          "卫星手机",
          "双卡手机",
          "翻新手机"
        ]
      },
      {
        name: "Tablets",
        nameZh: "平板电脑",
        icon: Tablet,
        count: 13,
        items: [
          "Standard Tablet",
          "Drawing Tablet",
          "E-Reader",
          "Kids Tablet",
          "Pro Tablet",
          "Mini Tablet",
          "Rugged Tablet",
          "Android Tablet",
          "Gaming Tablet",
          "Note Tablet",
          "Graphic Tablet",
          "Senior Tablet",
          "Dual-Screen"
        ],
        itemsZh: [
          "标准平板",
          "绘图板",
          "电子阅读器",
          "儿童平板",
          "专业平板",
          "迷你平板",
          "三防平板",
          "安卓平板",
          "游戏平板",
          "笔记平板",
          "图形绘制板",
          "老人平板",
          "双屏平板"
        ]
      },
      {
        name: "Cameras",
        nameZh: "相机",
        icon: Camera,
        count: 9,
        items: [
          "DSLR Camera",
          "Mirrorless",
          "Action Camera",
          "Instant Camera",
          "Cinema Camera",
          "Webcam",
          "Trail Camera",
          "Drone Camera",
          "Security Camera"
        ],
        itemsZh: [
          "单反相机",
          "微单相机",
          "运动相机",
          "拍立得相机",
          "电影摄影机",
          "网络摄像头",
          "野外监控相机",
          "无人机相机",
          "安防摄像头"
        ]
      },
      {
        name: "Audio",
        nameZh: "音频设备",
        icon: Sparkles,
        count: 9,
        items: [
          "Headphones",
          "Speakers",
          "Earbuds",
          "Soundbar",
          "Studio Monitor",
          "Microphone",
          "Turntable",
          "DAC / Amp",
          "Portable Speaker"
        ],
        itemsZh: [
          "头戴式耳机",
          "音箱",
          "入耳式耳机",
          "回音壁",
          "监听音箱",
          "麦克风",
          "黑胶唱机",
          "解码器/放大器",
          "便携音箱"
        ]
      },
      {
        name: "Drones",
        nameZh: "无人机",
        icon: LucideTicketsPlane,
        count: 14,
        items: [
          "Photo Drone",
          "Racing Drone",
          "Mini Drone",
          "Commercial Drone",
          "FPV Drone",
          "Mapping Drone",
          "Agricultural Drone",
          "Underwater Drone",
          "Delivery Drone",
          "Inspection Drone",
          "Thermal Drone",
          "Selfie Drone",
          "Lidar Drone",
          "Toy Drone"
        ],
        itemsZh: [
          "航拍无人机",
          "竞速无人机",
          "迷你无人机",
          "商用无人机",
          "第一视角无人机",
          "测绘无人机",
          "农业无人机",
          "水下无人机",
          "配送无人机",
          "巡检无人机",
          "热成像无人机",
          "自拍无人机",
          "激光雷达无人机",
          "玩具无人机"
        ]
      },
      {
        name: "Gaming",
        nameZh: "游戏设备",
        icon: Gamepad2,
        count: 9,
        items: [
          "Game Console",
          "VR Headset",
          "Gaming Monitor",
          "Handheld Console",
          "Gaming Mouse",
          "Mech Keyboard",
          "Gaming Chair",
          "Capture Card",
          "Controller"
        ],
        itemsZh: [
          "游戏主机",
          "VR头显",
          "游戏显示器",
          "掌机",
          "游戏鼠标",
          "机械键盘",
          "电竞椅",
          "采集卡",
          "游戏手柄"
        ]
      },
      {
        name: "Accessories",
        nameZh: "配件",
        icon: Cable,
        count: 9,
        items: [
          "Smartwatch",
          "Chargers",
          "Cables",
          "Cases & Covers",
          "Power Bank",
          "Screen Protector",
          "USB Hub",
          "Memory Card",
          "Wireless Charger"
        ],
        itemsZh: [
          "智能手表",
          "充电器",
          "数据线",
          "手机壳与保护套",
          "移动电源",
          "钢化膜",
          "USB集线器",
          "存储卡",
          "无线充电器"
        ]
      },
    ],
  },
  {
    id: "furniture",
    name: "Furniture",
    nameZh: "家居家具",
    icon: Sofa,
    accent: "#F97316",
    count: 76,
    subcategories: [
      {
        name: "Sofas",
        nameZh: "沙发",
        icon: Sofa,
        count: 15,
        items: [
          "Sectional Sofa",
          "Loveseat",
          "Recliner",
          "Sleeper Sofa",
          "Chesterfield",
          "Futon",
          "Modular Sofa",
          "Daybed",
          "Chaise Lounge",
          "Leather Sofa",
          "Corner Sofa",
          "Outdoor Sofa",
          "Tufted Sofa",
          "Velvet Sofa",
          "Power Recliner"
        ],
        itemsZh: [
          "组合沙发",
          "双人沙发",
          "躺椅沙发",
          "沙发床",
          "切斯特菲尔德沙发",
          "折叠沙发",
          "模块化沙发",
          "日间床",
          "贵妃躺椅",
          "皮质沙发",
          "转角沙发",
          "户外沙发",
          "绗缝沙发",
          "天鹅绒沙发",
          "电动躺椅"
        ]
      },
      {
        name: "Tables",
        nameZh: "桌子",
        icon: Table,
        count: 9,
        items: [
          "Dining Table",
          "Coffee Table",
          "Work Desk",
          "Side Table",
          "Console Table",
          "Dining Set",
          "Folding Table",
          "Pub Table",
          "Nesting Tables"
        ],
        itemsZh: [
          "餐桌",
          "咖啡桌",
          "工作桌",
          "边桌",
          "玄关桌",
          "餐桌套装",
          "折叠桌",
          "酒吧桌",
          "套叠桌"
        ]
      },
      {
        name: "Chairs",
        nameZh: "椅子",
        icon: Armchair,
        count: 9,
        items: [
          "Office Chair",
          "Dining Chair",
          "Accent Chair",
          "Bar Stool",
          "Rocking Chair",
          "Ergonomic Chair",
          "Folding Chair",
          "Bean Bag",
          "Lounge Chair"
        ],
        itemsZh: [
          "办公椅",
          "餐椅",
          "装饰椅",
          "吧台凳",
          "摇椅",
          "人体工学椅",
          "折叠椅",
          "懒人沙发",
          "休闲椅"
        ]
      },
      {
        name: "Beds",
        nameZh: "床",
        icon: BedDouble,
        count: 9,
        items: [
          "King Bed",
          "Queen Bed",
          "Bunk Bed",
          "Platform Bed",
          "Murphy Bed",
          "Toddler Bed",
          "Adjustable Bed",
          "Canopy Bed",
          "Storage Bed"
        ],
        itemsZh: [
          "特大床",
          "大床",
          "双层床",
          "平台床",
          "壁床",
          "幼儿床",
          "可调节床",
          "四柱床",
          "储物床"
        ]
      },
      {
        name: "Storage",
        nameZh: "收纳家具",
        icon: Boxes,
        count: 8,
        items: [
          "Bookshelf",
          "Wardrobe",
          "Cabinet",
          "Chest of Drawers",
          "Shoe Rack",
          "TV Stand",
          "Curio Cabinet",
          "Storage Ottoman"
        ],
        itemsZh: [
          "书架",
          "衣柜",
          "橱柜",
          "抽屉柜",
          "鞋架",
          "电视柜",
          "展示柜",
          "收纳脚凳"
        ]
      },
      {
        name: "Outdoor",
        nameZh: "户外家具",
        icon: Trees,
        count: 9,
        items: [
          "Patio Set",
          "Hammock",
          "Garden Bench",
          "Patio Umbrella",
          "Outdoor Sofa",
          "Fire Pit Table",
          "Swing Chair",
          "Adirondack Chair",
          "Gazebo"
        ],
        itemsZh: [
          "庭院家具套装",
          "吊床",
          "花园长椅",
          "庭院遮阳伞",
          "户外沙发",
          "火盆桌",
          "秋千椅",
          "阿迪朗达克椅",
          "凉亭"
        ]
      },
      {
        name: "Office",
        nameZh: "办公家具",
        icon: Monitor,
        count: 8,
        items: [
          "Standing Desk",
          "Filing Cabinet",
          "Whiteboard",
          "Desk Organizer",
          "Bookcase",
          "Conference Table",
          "Monitor Arm",
          "Desk Mat"
        ],
        itemsZh: [
          "站立办公桌",
          "文件柜",
          "白板",
          "桌面收纳",
          "书柜",
          "会议桌",
          "显示器支架",
          "桌垫"
        ]
      },
      {
        name: "Lighting",
        nameZh: "照明",
        icon: Lightbulb,
        count: 9,
        items: [
          "Pendant Light",
          "Floor Lamp",
          "Table Lamp",
          "Chandelier",
          "Wall Sconce",
          "LED Strips",
          "Track Lighting",
          "Desk Lamp",
          "Smart Bulbs"
        ],
        itemsZh: [
          "吊灯",
          "落地灯",
          "台灯",
          "枝形吊灯",
          "壁灯",
          "LED灯带",
          "轨道灯",
          "书桌灯",
          "智能灯泡"
        ]
      }
    ],
  },
  {
    id: "energy",
    name: "Energy",
    nameZh: "新能源",
    icon: Sun,
    accent: "#FBBF24",
    count: 61,
    subcategories: [
      {
        name: "Solar Systems",
        nameZh: "太阳能系统",
        icon: Sun,
        count: 9,
        items: [
          "Residential Panel",
          "Commercial Panel",
          "Portable Panel",
          "Roof-Mount Kit",
          "Thin-Film Panel",
          "Bifacial Panel",
          "Solar Tiles",
          "Tracking Mount",
          "Solar Carport"
        ],
        itemsZh: [
          "住宅太阳能板",
          "商用太阳能板",
          "便携式太阳能板",
          "屋顶安装套件",
          "薄膜太阳能板",
          "双面太阳能板",
          "太阳能瓦片",
          "追踪支架",
          "太阳能车棚"
        ]
      },
      {
        name: "Batteries",
        nameZh: "电池与储能",
        icon: BatteryCharging,
        count: 9,
        items: [
          "Lithium Battery",
          "Lead-Acid",
          "Home Battery",
          "Industrial Cell",
          "Flow Battery",
          "Solid-State Cell",
          "Portable Power",
          "Nickel-MH",
          "Battery BMS"
        ],
        itemsZh: [
          "锂电池",
          "铅酸电池",
          "家用储能电池",
          "工业电芯",
          "液流电池",
          "固态电池",
          "便携式电源",
          "镍氢电池",
          "电池管理系统"
        ]
      },
      {
        name: "Inverters",
        nameZh: "逆变器",
        icon: Zap,
        count: 8,
        items: [
          "String Inverter",
          "Micro Inverter",
          "Hybrid Inverter",
          "Off-Grid",
          "Three-Phase",
          "Grid-Tie",
          "Power Optimizer",
          "Charger Inverter"
        ],
        itemsZh: [
          "组串式逆变器",
          "微型逆变器",
          "混合逆变器",
          "离网逆变器",
          "三相逆变器",
          "并网逆变器",
          "功率优化器",
          "充电逆变器"
        ]
      },
      {
        name: "Wind Energy",
        nameZh: "风能设备",
        icon: Wind,
        count: 13,
        items: [
          "Wind Turbine",
          "Micro Wind",
          "Vertical Axis",
          "Residential Kit",
          "Offshore Turbine",
          "Hybrid Wind-Solar",
          "Wind Monitor",
          "Tower Kit",
          "Bladeless Turbine",
          "Rooftop Wind",
          "Wind Controller",
          "Marine Turbine",
          "Wind Farm Kit"
        ],
        itemsZh: [
          "风力发电机",
          "微型风电",
          "垂直轴风机",
          "家用套件",
          "海上风机",
          "风光混合系统",
          "风能监测器",
          "塔架套件",
          "无叶片风机",
          "屋顶风机",
          "风能控制器",
          "海洋风机",
          "风电场套件"
        ]
      },
      {
        name: "Generators",
        nameZh: "发电机",
        icon: Gauge,
        count: 13,
        items: [
          "Diesel Generator",
          "Gas Generator",
          "Portable Unit",
          "Standby System",
          "Inverter Generator",
          "Dual-Fuel Gen",
          "Solar Generator",
          "Industrial Gen",
          "Marine Generator",
          "Propane Generator",
          "Hydrogen Gen",
          "Transfer Switch",
          "RV Generator"
        ],
        itemsZh: [
          "柴油发电机",
          "燃气发电机",
          "便携式机组",
          "备用电源系统",
          "逆变发电机",
          "双燃料发电机",
          "太阳能发电机",
          "工业发电机",
          "船用发电机",
          "丙烷发电机",
          "氢能发电机",
          "自动转换开关",
          "房车发电机"
        ]
      },
      {
        name: "EV Charging",
        nameZh: "电动车充电",
        icon: Plug,
        count: 9,
        items: [
          "Home Charger",
          "Fast Charger",
          "Charging Station",
          "Portable Charger",
          "Level 2 Charger",
          "Solar EV Charger",
          "Fleet Charger",
          "Wireless Charger",
          "Smart Charger"
        ],
        itemsZh: [
          "家用充电器",
          "快速充电器",
          "充电站",
          "便携式充电器",
          "二级充电器",
          "太阳能电动车充电器",
          "车队充电器",
          "无线充电器",
          "智能充电器"
        ]
      },
    ],
  },
  {
    id: "apparel",
    name: "Apparel",
    nameZh: "服饰服装",
    icon: Shirt,
    accent: "#FB7185",
    count: 149,
    subcategories: [
      {
        name: "Men's Wear",
        nameZh: "男装",
        icon: Shirt,
        count: 15,
        items: [
          "Shirts",
          "Suits",
          "Jeans",
          "Jackets",
          "Polo Shirts",
          "Trousers",
          "Hoodies",
          "Shorts",
          "Overcoats",
          "Sweaters",
          "Tank Tops",
          "Vests",
          "Cargo Pants",
          "Linen Shirts",
          "Leather Jackets"
        ],
        itemsZh: [
          "衬衫",
          "西装",
          "牛仔裤",
          "夹克",
          "Polo衫",
          "长裤",
          "连帽衫",
          "短裤",
          "大衣",
          "毛衣",
          "背心",
          "马甲",
          "工装裤",
          "亚麻衬衫",
          "皮夹克"
        ]
      },
      {
        name: "Women's Wear",
        nameZh: "女装",
        icon: Shirt,
        count: 15,
        items: [
          "Dresses",
          "Blouses",
          "Skirts",
          "Coats",
          "Jumpsuits",
          "Cardigans",
          "Leggings",
          "Blazers",
          "Maxi Dress",
          "Crop Tops",
          "Wrap Dresses",
          "Trench Coats",
          "Palazzo Pants",
          "Rompers",
          "Knitwear"
        ],
        itemsZh: [
          "连衣裙",
          "女式衬衫",
          "裙子",
          "外套",
          "连体裤",
          "开衫",
          "打底裤",
          "西装外套",
          "长款连衣裙",
          "短上衣",
          "裹身裙",
          "风衣",
          "阔腿裤",
          "连体短裤",
          "针织衫"
        ]
      },
      {
        name: "Kids",
        nameZh: "童装",
        icon: Baby,
        count: 14,
        items: [
          "Onesies",
          "T-Shirts",
          "School Wear",
          "Play Wear",
          "Winter Jackets",
          "Rain Gear",
          "Pajamas",
          "Swimwear",
          "Hoodies",
          "Costumes",
          "Sports Wear",
          "Formal Wear",
          "Shoes",
          "Accessories"
        ],
        itemsZh: [
          "连体衣",
          "T恤",
          "校服",
          "休闲服",
          "冬季夹克",
          "雨具",
          "睡衣",
          "泳装",
          "连帽衫",
          "服装道具",
          "运动服",
          "正装",
          "鞋子",
          "配饰"
        ]
      },
      {
        name: "Shoes",
        nameZh: "鞋类",
        icon: Footprints,
        count: 9,
        items: [
          "Sneakers",
          "Boots",
          "Heels",
          "Sandals",
          "Loafers",
          "Running Shoes",
          "Slides",
          "Dress Shoes",
          "Hiking Boots"
        ],
        itemsZh: [
          "运动鞋",
          "靴子",
          "高跟鞋",
          "凉鞋",
          "乐福鞋",
          "跑鞋",
          "拖鞋",
          "正装鞋",
          "登山靴"
        ]
      },
      {
        name: "Bags",
        nameZh: "箱包",
        icon: Wallet,
        count: 9,
        items: [
          "Backpack",
          "Handbag",
          "Duffle Bag",
          "Travel Bag",
          "Crossbody",
          "Tote Bag",
          "Laptop Bag",
          "Clutch",
          "Messenger Bag"
        ],
        itemsZh: [
          "背包",
          "手提包",
          "运动旅行包",
          "旅行包",
          "斜挎包",
          "托特包",
          "电脑包",
          "手拿包",
          "邮差包"
        ]
      },
      {
        name: "Sportswear",
        nameZh: "运动服饰",
        icon: Dumbbell,
        count: 14,
        items: [
          "Activewear",
          "Yoga Wear",
          "Running Gear",
          "Swimwear",
          "Gym Shorts",
          "Compression Wear",
          "Sports Bras",
          "Track Suits",
          "Cycling Gear",
          "Ski Wear",
          "Tennis Wear",
          "Golf Wear",
          "Basketball Gear",
          "Hiking Wear"
        ],
        itemsZh: [
          "运动服",
          "瑜伽服",
          "跑步装备",
          "泳装",
          "健身短裤",
          "压缩衣",
          "运动内衣",
          "运动套装",
          "骑行装备",
          "滑雪服",
          "网球服",
          "高尔夫服",
          "篮球装备",
          "徒步服"
        ]
      },
      {
        name: "Formal",
        nameZh: "正装礼服",
        icon: Shirt,
        count: 14,
        items: [
          "Tuxedos",
          "Evening Gowns",
          "Dress Shoes",
          "Ties & Bowties",
          "Cufflinks",
          "Pocket Squares",
          "Waistcoats",
          "Formal Belts",
          "Suspenders",
          "Dress Shirts",
          "Formal Watches",
          "Top Hats",
          "Wedding Suits",
          "Cocktail Dresses"
        ],
        itemsZh: [
          "燕尾服",
          "晚礼服",
          "正装鞋",
          "领带与领结",
          "袖扣",
          "口袋巾",
          "马甲",
          "正装皮带",
          "吊带",
          "正装衬衫",
          "正装手表",
          "礼帽",
          "婚礼西装",
          "鸡尾酒礼服"
        ]
      },
      {
        name: "Accessories",
        nameZh: "配饰",
        icon: Watch,
        count: 9,
        items: [
          "Watches",
          "Belts",
          "Sunglasses",
          "Jewelry",
          "Scarves",
          "Hats & Caps",
          "Wallets",
          "Gloves",
          "Hair Accessories"
        ],
        itemsZh: [
          "手表",
          "皮带",
          "太阳镜",
          "珠宝",
          "围巾",
          "帽子与鸭舌帽",
          "钱包",
          "手套",
          "发饰"
        ]
      },
      {
        name: "Fabrics",
        nameZh: "面料",
        icon: Zap,
        count: 9,
        items: [
          "Cotton Fabric",
          "Polyester",
          "Wool Fabric",
          "Nylon",
          "Chiffon",
          "Velvet",
          "Canvas",
          "Jersey Knit",
          "Organza"
        ],
        itemsZh: [
          "棉布",
          "涤纶",
          "羊毛面料",
          "尼龙",
          "雪纺",
          "天鹅绒",
          "帆布",
          "针织布",
          "欧根纱"
        ]
      },
      {
        name: "Yarn",
        nameZh: "纱线",
        icon: WholeWord,
        count: 8,
        items: [
          "Cotton Yarn",
          "Acrylic Yarn",
          "Wool Yarn",
          "Silk Yarn",
          "Bamboo Yarn",
          "Cashmere Yarn",
          "Mohair Yarn",
          "Blended Yarn"
        ],
        itemsZh: [
          "棉纱",
          "腈纶纱",
          "羊毛纱",
          "丝纱",
          "竹纤维纱",
          "羊绒纱",
          "马海毛纱",
          "混纺纱"
        ]
      },
      {
        name: "Leather",
        nameZh: "皮革类型",
        icon: Shield,
        count: 9,
        items: [
          "Full Grain",
          "Suede",
          "Bonded Leather",
          "Faux Leather",
          "Nubuck",
          "Patent Leather",
          "Tooling Leather",
          "Exotic Leather",
          "Leather Dye"
        ],
        itemsZh: [
          "全粒面皮",
          "绒面革",
          "复合皮",
          "人造皮革",
          "磨砂皮",
          "漆皮",
          "植鞣革",
          "异域皮革",
          "皮革染料"
        ]
      },
      {
        name: "Silk",
        nameZh: "丝绸类型",
        icon: Feather,
        count: 8,
        items: [
          "Mulberry Silk",
          "Raw Silk",
          "Silk Blend",
          "Charmeuse",
          "Dupioni Silk",
          "Silk Satin",
          "Habotai Silk",
          "Silk Chiffon"
        ],
        itemsZh: [
          "桑蚕丝",
          "生丝",
          "丝混纺",
          "乔其绉",
          "双宫丝",
          "丝绸缎",
          "羽二重丝",
          "丝绸雪纺"
        ]
      },
      {
        name: "Denim Types",
        nameZh: "牛仔面料类型",
        icon: Shirt,
        count: 8,
        items: [
          "Raw Denim",
          "Stretch Denim",
          "Selvedge Denim",
          "Organic Denim",
          "Washed Denim",
          "Bull Denim",
          "Chambray",
          "Black Denim"
        ],
        itemsZh: [
          "原色牛仔布",
          "弹力牛仔布",
          "赤耳牛仔布",
          "有机牛仔布",
          "水洗牛仔布",
          "重磅牛仔布",
          "府绸牛仔",
          "黑色牛仔布"
        ]
      },
      {
        name: "Linen ",
        nameZh: "亚麻类型",
        icon: Leaf,
        count: 8,
        items: [
          "Pure Linen",
          "Linen Blend",
          "Washed Linen",
          "Belgian Linen",
          "Linen Canvas",
          "Handkerchief Linen",
          "Linen Burlap",
          "Irish Linen"
        ],
        itemsZh: [
          "纯亚麻",
          "亚麻混纺",
          "水洗亚麻",
          "比利时亚麻",
          "亚麻帆布",
          "手帕亚麻",
          "亚麻粗麻布",
          "爱尔兰亚麻"
        ]
      },
    ],
  },
  {
    id: "beauty",
    name: "Beauty",
    nameZh: "美妆个护",
    icon: Palette,
    accent: "#EC4899",
    count: 58,
    subcategories: [
      {
        name: "Skincare",
        nameZh: "护肤品",
        icon: Sparkles,
        count: 9,
        items: [
          "Moisturizer",
          "Serum",
          "Cleanser",
          "Sunscreen",
          "Toner",
          "Eye Cream",
          "Face Mask",
          "Exfoliator",
          "Retinol Cream"
        ],
        itemsZh: [
          "保湿霜",
          "精华液",
          "洁面乳",
          "防晒霜",
          "爽肤水",
          "眼霜",
          "面膜",
          "去角质产品",
          "视黄醇面霜"
        ]
      },
      {
        name: "Makeup",
        nameZh: "彩妆",
        icon: Palette,
        count: 9,
        items: [
          "Foundation",
          "Lipstick",
          "Mascara",
          "Blush",
          "Concealer",
          "Eyeshadow Palette",
          "Setting Spray",
          "Eyeliner",
          "Bronzer"
        ],
        itemsZh: [
          "粉底",
          "口红",
          "睫毛膏",
          "腮红",
          "遮瑕膏",
          "眼影盘",
          "定妆喷雾",
          "眼线笔",
          "修容粉"
        ]
      },
      {
        name: "Hair Care",
        nameZh: "护发用品",
        icon: Scissors,
        count: 9,
        items: [
          "Shampoo",
          "Conditioner",
          "Hair Oil",
          "Styling Tools",
          "Hair Mask",
          "Dry Shampoo",
          "Hair Color",
          "Leave-In Spray",
          "Scalp Treatment"
        ],
        itemsZh: [
          "洗发水",
          "护发素",
          "护发精油",
          "造型工具",
          "发膜",
          "干发喷雾",
          "染发剂",
          "免洗喷雾",
          "头皮护理"
        ]
      },
      {
        name: "Fragrance",
        nameZh: "香氛",
        icon: Sparkles,
        count: 9,
        items: [
          "Perfume",
          "Cologne",
          "Body Mist",
          "Essential Oil",
          "Roll-On Perfume",
          "Scented Candle",
          "Room Spray",
          "Incense",
          "Diffuser"
        ],
        itemsZh: [
          "香水",
          "古龙水",
          "身体喷雾",
          "精油",
          "滚珠香水",
          "香薰蜡烛",
          "室内喷雾",
          "香",
          "香薰扩香器"
        ]
      },
      {
        name: "Nail",
        nameZh: "美甲护理",
        icon: Hand,
        count: 13,
        items: [
          "Nail Polish",
          "Gel Kit",
          "Nail Art",
          "Care Kit",
          "Press-On Nails",
          "UV Lamp",
          "Cuticle Oil",
          "Nail Stickers",
          "Nail Drills",
          "Base & Top Coat",
          "Acrylic Powder",
          "Nail Forms",
          "Dipping Powder"
        ],
        itemsZh: [
          "指甲油",
          "凝胶套装",
          "美甲艺术",
          "护理套装",
          "穿戴甲",
          "UV灯",
          "指缘油",
          "美甲贴纸",
          "美甲打磨机",
          "底油与封层",
          "丙烯粉",
          "甲片模板",
          "浸粉美甲"
        ]
      },
      {
        name: "Wellness",
        nameZh: "健康养生",
        icon: Leaf,
        count: 9,
        items: [
          "Vitamins",
          "Supplements",
          "Aromatherapy",
          "Massage Tools",
          "Jade Roller",
          "Bath Salts",
          "Sleep Aids",
          "Yoga Mat",
          "Meditation App"
        ],
        itemsZh: [
          "维生素",
          "营养补充剂",
          "芳香疗法",
          "按摩工具",
          "玉石滚轮",
          "浴盐",
          "助眠产品",
          "瑜伽垫",
          "冥想应用"
        ]
      },
    ],
  },
  {
    id: "mining",
    name: "Mining",
    nameZh: "矿业",
    icon: Gem,
    accent: "#3B82F6",
    count: 64,
    subcategories: [
      {
        name: "Industrial Minerals",
        nameZh: "工业矿物",
        icon: Gem,
        count: 9,
        items: [
          "Quartz",
          "Limestone",
          "Gypsum",
          "Feldspar",
          "Mica",
          "Barite",
          "Dolomite",
          "Silica Sand",
          "Talc"
        ],
        itemsZh: [
          "石英",
          "石灰石",
          "石膏",
          "长石",
          "云母",
          "重晶石",
          "白云石",
          "硅砂",
          "滑石"
        ]
      },
      {
        name: "Metal Ores",
        nameZh: "金属矿石",
        icon: Pickaxe,
        count: 9,
        items: [
          "Gold Ore",
          "Iron Ore",
          "Copper Ore",
          "Silver Ore",
          "Platinum Ore",
          "Lithium",
          "Zinc Ore",
          "Cobalt Ore",
          "Tin Ore"
        ],
        itemsZh: [
          "金矿石",
          "铁矿石",
          "铜矿石",
          "银矿石",
          "铂矿石",
          "锂矿",
          "锌矿石",
          "钴矿石",
          "锡矿石"
        ]
      },
      {
        name: "Excavation",
        nameZh: "重型机械",
        icon: Truck,
        count: 8,
        items: [
          "Excavator",
          "Bucket Loader",
          "Dragline",
          "Tunneling Rig",
          "Haul Truck",
          "Scraper",
          "Dredger",
          "Trencher"
        ],
        itemsZh: [
          "挖掘机",
          "铲斗装载机",
          "绳斗挖掘机",
          "掘进设备",
          "矿用卡车",
          "铲运机",
          "挖泥船",
          "沟槽机"
        ]
      },
      {
        name: "Drilling Equipment",
        nameZh: "钻探设备",
        icon: Drill,
        count: 8,
        items: [
          "Drill Bits",
          "Core Sampler",
          "Pneumatic Drill",
          "Rotary Drill",
          "Diamond Drill",
          "DTH Hammer",
          "Drill Rods",
          "Mud Pumps"
        ],
        itemsZh: [
          "钻头",
          "岩芯取样器",
          "气动钻机",
          "旋转钻机",
          "金刚石钻机",
          "潜孔锤",
          "钻杆",
          "泥浆泵"
        ]
      },
      {
        name: "Processing",
        nameZh: "矿物加工设备",
        icon: Settings,
        count: 9,
        items: [
          "Crusher",
          "Ball Mill",
          "Flotation Cell",
          "Screening Machine",
          "Magnetic Separator",
          "Centrifuge",
          "Thickener",
          "Leaching Tank",
          "Conveyor System"
        ],
        itemsZh: [
          "破碎机",
          "球磨机",
          "浮选机",
          "筛分机",
          "磁选机",
          "离心机",
          "浓密机",
          "浸出槽",
          "输送系统"
        ]
      },
      {
        name: "Safety",
        nameZh: "矿山安全",
        icon: Shield,
        count: 9,
        items: [
          "Gas Detector",
          "Rescue Kit",
          "Ventilation Fan",
          "Headlamp",
          "Self-Rescuer",
          "Dust Suppressor",
          "Fire Extinguisher",
          "Communication Radio",
          "PPE Bundle"
        ],
        itemsZh: [
          "气体检测仪",
          "救援套件",
          "通风风机",
          "头灯",
          "自救器",
          "抑尘设备",
          "灭火器",
          "通信无线电",
          "个人防护装备套装"
        ]
      },
    ],
  },
  {
    id: "agriculture",
    name: "Agriculture",
    nameZh: "农业",
    icon: Wheat,
    accent: "#22C55E",
    count: 72,
    subcategories: [
      {
        name: "Grains",
        nameZh: "谷物",
        icon: Wheat,
        count: 9,
        items: [
          "Wheat",
          "Rice",
          "Corn",
          "Oats",
          "Barley",
          "Millet",
          "Sorghum",
          "Quinoa",
          "Rye"
        ],
        itemsZh: [
          "小麦",
          "大米",
          "玉米",
          "燕麦",
          "大麦",
          "小米",
          "高粱",
          "藜麦",
          "黑麦"
        ]
      },
      {
        name: "Fruits",
        nameZh: "水果",
        icon: Apple,
        count: 40,
        items: [
          "Oranges",
          "Lemons",
          "Limes",
          "Grapefruits",
          "Tangerines",
          "Mangoes",
          "Pineapples",
          "Papayas",
          "Passion Fruit",
          "Dragon Fruit",
          "Strawberries",
          "Blueberries",
          "Raspberries",
          "Blackberries",
          "Cranberries",
          "Peaches",
          "Plums",
          "Cherries",
          "Apricots",
          "Nectarines",
          "Grapes",
          "Bananas",
          "Apples",
          "Pears",
          "Avocados",
          "Watermelons",
          "Cantaloupes",
          "Honeydew Melon",
          "Pomegranates",
          "Figs",
          "Dates",
          "Coconuts",
          "Guavas",
          "Lychees",
          "Kiwi Fruit",
          "Persimmons",
          "Jackfruit",
          "Durian",
          "Star Fruit",
          "Plantains"
        ],
        itemsZh: [
          "橙子",
          "柠檬",
          "青柠",
          "葡萄柚",
          "橘子",
          "芒果",
          "菠萝",
          "木瓜",
          "百香果",
          "火龙果",
          "草莓",
          "蓝莓",
          "树莓",
          "黑莓",
          "蔓越莓",
          "桃子",
          "李子",
          "樱桃",
          "杏",
          "油桃",
          "葡萄",
          "香蕉",
          "苹果",
          "梨",
          "牛油果",
          "西瓜",
          "哈密瓜",
          "蜜瓜",
          "石榴",
          "无花果",
          "枣",
          "椰子",
          "番石榴",
          "荔枝",
          "猕猴桃",
          "柿子",
          "菠萝蜜",
          "榴莲",
          "杨桃",
          "大蕉"
        ]
      },
      {
        name: "Vegetables",
        nameZh: "蔬菜与香草",
        icon: Leaf,
        count: 45,
        items: [
          "Carrots",
          "Potatoes",
          "Sweet Potatoes",
          "Beets",
          "Turnips",
          "Radishes",
          "Spinach",
          "Lettuce",
          "Kale",
          "Swiss Chard",
          "Arugula",
          "Cabbage",
          "Broccoli",
          "Cauliflower",
          "Brussels Sprouts",
          "Green Beans",
          "Peas",
          "Lentils",
          "Chickpeas",
          "Soybeans",
          "Tomatoes",
          "Bell Peppers",
          "Chili Peppers",
          "Jalapeños",
          "Onions",
          "Garlic",
          "Shallots",
          "Leeks",
          "Cucumbers",
          "Zucchini",
          "Pumpkins",
          "Butternut Squash",
          "Eggplant",
          "Celery",
          "Asparagus",
          "Artichokes",
          "Mushrooms",
          "Corn on the Cob",
          "Okra",
          "Ginger",
          "Turmeric",
          "Basil",
          "Cilantro",
          "Parsley",
          "Mint"
        ],
        itemsZh: [
          "胡萝卜",
          "土豆",
          "红薯",
          "甜菜",
          "芜菁",
          "萝卜",
          "菠菜",
          "生菜",
          "羽衣甘蓝",
          "瑞士甜菜",
          "芝麻菜",
          "卷心菜",
          "西兰花",
          "菜花",
          "抱子甘蓝",
          "四季豆",
          "豌豆",
          "扁豆",
          "鹰嘴豆",
          "大豆",
          "西红柿",
          "甜椒",
          "辣椒",
          "墨西哥辣椒",
          "洋葱",
          "大蒜",
          "红葱头",
          "韭葱",
          "黄瓜",
          "西葫芦",
          "南瓜",
          "冬南瓜",
          "茄子",
          "芹菜",
          "芦笋",
          "洋蓟",
          "蘑菇",
          "玉米棒",
          "秋葵",
          "姜",
          "姜黄",
          "罗勒",
          "香菜",
          "欧芹",
          "薄荷"
        ]
      },
      {
        name: "Seeds",
        nameZh: "种子",
        icon: Sprout,
        count: 8,
        items: [
          "Vegetable Seeds",
          "Flower Seeds",
          "Tree Seeds",
          "Organic Seeds",
          "Grass Seeds",
          "Herb Seeds",
          "Hybrid Seeds",
          "Cover Crop Seeds"
        ],
        itemsZh: [
          "蔬菜种子",
          "花卉种子",
          "树木种子",
          "有机种子",
          "草种",
          "草本种子",
          "杂交种子",
          "覆盖作物种子"
        ]
      },
      {
        name: "Fertilizers",
        nameZh: "肥料",
        icon: Droplets,
        count: 9,
        items: [
          "Nitrogen Mix",
          "Organic Compost",
          "Phosphate",
          "Potash",
          "Urea",
          "Micronutrients",
          "Liquid Fertilizer",
          "Slow Release",
          "Biofertilizer"
        ],
        itemsZh: [
          "氮肥混合物",
          "有机堆肥",
          "磷肥",
          "钾肥",
          "尿素",
          "微量元素肥",
          "液体肥料",
          "缓释肥",
          "生物肥料"
        ]
      },
      {
        name: "Agricultural Machinery",
        nameZh: "农业机械",
        icon: Tractor,
        count: 9,
        items: [
          "Tractor",
          "Harvester",
          "Irrigation System",
          "Seeder",
          "Plow",
          "Sprayer",
          "Baler",
          "Grain Dryer",
          "Greenhouse Kit"
        ],
        itemsZh: [
          "拖拉机",
          "收割机",
          "灌溉系统",
          "播种机",
          "犁",
          "喷雾机",
          "打捆机",
          "谷物干燥机",
          "温室套件"
        ]
      },
      {
        name: "Livestock & Farming",
        nameZh: "畜牧养殖",
        icon: PawPrint,
        count: 9,
        items: [
          "Cattle",
          "Poultry",
          "Sheep",
          "Fish Stock",
          "Goats",
          "Pigs",
          "Horses",
          "Bees & Hives",
          "Feed & Hay"
        ],
        itemsZh: [
          "牛",
          "家禽",
          "绵羊",
          "鱼类养殖",
          "山羊",
          "猪",
          "马",
          "蜜蜂与蜂箱",
          "饲料与干草"
        ]
      },
    ],
  },
  {
    id: "sports",
    name: "Sports",
    nameZh: "体育运动",
    icon: Volleyball,
    accent: "#14B8A6",
    count: 55,
    subcategories: [
      {
        name: "Sports Equipment",
        nameZh: "体育器材",
        icon: Trophy,
        count: 9,
        items: [
          "Basketballs",
          "Soccer Balls",
          "Footballs",
          "Volleyball",
          "Baseball Bats",
          "Hockey Sticks",
          "Cricket Gear",
          "Rugby Balls",
          "Team Jerseys"
        ],
        itemsZh: [
          "篮球",
          "足球",
          "橄榄球",
          "排球",
          "棒球棒",
          "曲棍球杆",
          "板球装备",
          "橄榄球",
          "队服"
        ]
      },
      {
        name: "Fitness Equipment",
        nameZh: "健身器材",
        icon: Dumbbell,
        count: 9,
        items: [
          "Dumbbells",
          "Kettlebells",
          "Resistance Bands",
          "Yoga Mats",
          "Treadmills",
          "Spin Bikes",
          "Rowing Machines",
          "Pull-Up Bars",
          "Jump Ropes"
        ],
        itemsZh: [
          "哑铃",
          "壶铃",
          "阻力带",
          "瑜伽垫",
          "跑步机",
          "动感单车",
          "划船机",
          "引体向上杆",
          "跳绳"
        ]
      },
      {
        name: "Outdoor Gear",
        nameZh: "户外装备",
        icon: Tent,
        count: 9,
        items: [
          "Hiking Poles",
          "Climbing Gear",
          "Camping Tents",
          "Kayaks",
          "Fishing Rods",
          "Binoculars",
          "Sleeping Bags",
          "Backpacks",
          "Surfboards"
        ],
        itemsZh: [
          "登山杖",
          "攀岩装备",
          "露营帐篷",
          "皮划艇",
          "钓鱼竿",
          "望远镜",
          "睡袋",
          "背包",
          "冲浪板"
        ]
      },
      {
        name: "Racquet Sports",
        nameZh: "球拍运动",
        icon: Activity,
        count: 8,
        items: [
          "Tennis Rackets",
          "Badminton Sets",
          "Table Tennis",
          "Squash Rackets",
          "Tennis Balls",
          "Shuttlecocks",
          "Racket Bags",
          "Grip Tape"
        ],
        itemsZh: [
          "网球拍",
          "羽毛球套装",
          "乒乓球",
          "壁球拍",
          "网球",
          "羽毛球",
          "球拍包",
          "手胶"
        ]
      },
      {
        name: "Winter Sports",
        nameZh: "冬季运动",
        icon: Snowflake,
        count: 8,
        items: [
          "Skis",
          "Snowboards",
          "Ski Boots",
          "Snow Goggles",
          "Ice Skates",
          "Ski Poles",
          "Snow Helmets",
          "Thermal Layers"
        ],
        itemsZh: [
          "滑雪板",
          "单板滑雪",
          "滑雪靴",
          "雪镜",
          "冰刀鞋",
          "滑雪杖",
          "滑雪头盔",
          "保暖内衣"
        ]
      },
      {
        name: "Sports Accessories",
        nameZh: "运动配件",
        icon: Watch,
        count: 9,
        items: [
          "Sports Watches",
          "Fitness Trackers",
          "Sports Bags",
          "Sweatbands",
          "Sports Glasses",
          "Knee Braces",
          "Grip Gloves",
          "Compression Socks",
          "Hydration"
        ],
        itemsZh: [
          "运动手表",
          "健身追踪器",
          "运动包",
          "护腕带",
          "运动眼镜",
          "护膝",
          "防滑手套",
          "压缩袜",
          "补水装备"
        ]
      },
    ],
  },
];

export const homeNavOrder = [
  "vehicles",
  "industrial",
  "hardware",
  "electronics",
  "furniture",
  "energy",
  "apparel",
  "beauty",
  "mining",
  "agriculture",
  "sports",
] as const;
