import type { LucideIcon } from "lucide-react";
import {
  Car,
  Factory,
  Hammer,
  Monitor,
  Sofa,
  Shirt,
  Palette,
  Gem,
  Wheat,
  Volleyball,
  Truck,
  Wrench,
  Boxes,
  ShieldCheck,
  Package,
  Cog,
  Zap,
  Drill,
  HardHat,
  Cpu,
  Smartphone,
  Tablet,
  BedDouble,
  Table,
  Armchair,
  BatteryCharging,
  PlugZap,
  Sun,
  User,
  Sparkles,
  Leaf,
  Tractor,
  Droplets,
  Mountain,
  Pickaxe,
  Eye,
  Building2,
  FlaskConical,
  PawPrint,
  Watch,
  Footprints,
  Trophy,
  Dumbbell,
  Globe,
} from "lucide-react";

export type Subcategory = {
  name: string;
  icon: LucideIcon;
  items: string[];
  count: number;
};

export type Category = {
  id: string;
  name: string;
  icon: LucideIcon;
  accent: string;
  count: number;
  subcategories: Subcategory[];
};

export const categories: Category[] = [
  {
    id: "vehicles",
    name: "Vehicles",
    icon: Car,
    accent: "#3B82F6",
    count: 111,
    subcategories: [
      { name: "SUV", icon: Car, count: 18, items: ["Electric SUV", "Hybrid SUV", "Compact SUV", "Luxury SUV", "7-Seater", "+13 more"] },
      { name: "Electric", icon: Zap, count: 22, items: ["Electric Sedan", "Electric SUV", "Electric Truck", "Luxury EV", "Fleet EV", "+17 more"] },
      { name: "Pickup Truck", icon: Truck, count: 14, items: ["4x4 Pickup", "Work Truck", "Diesel Pickup", "Electric Pickup", "+10 more"] },
      { name: "Sedan", icon: Car, count: 11, items: ["Compact Sedan", "Executive Sedan", "Electric Sedan", "+8 more"] },
      { name: "Truck", icon: Truck, count: 9, items: ["Box Truck", "Flatbed", "Reefer", "+6 more"] },
      { name: "Parts", icon: Wrench, count: 37, items: ["Tires", "Brake Kits", "Batteries", "Lighting", "+33 more"] },
    ],
  },
  {
    id: "industrial",
    name: "Industrial",
    icon: Factory,
    accent: "#6366F1",
    count: 76,
    subcategories: [
      { name: "Machinery", icon: Cog, count: 15, items: ["CNC Machine", "Lathe", "Hydraulic Press", "Conveyor Belt", "+11 more"] },
      { name: "Raw Materials", icon: Boxes, count: 9, items: ["Aluminum", "Steel", "Copper", "Polymers", "+8 more"] },
      { name: "Chemicals", icon: FlaskConical, count: 12, items: ["Solvents", "Resins", "Adhesives", "Coatings", "+9 more"] },
      { name: "Packaging", icon: Package, count: 8, items: ["Corrugate", "Pouches", "Labels", "Stretch Film", "+6 more"] },
      { name: "Safety Gear", icon: HardHat, count: 10, items: ["Gloves", "Respirators", "Safety Glasses", "Harnesses", "+7 more"] },
      { name: "Power Tools", icon: Drill, count: 7, items: ["Impact Driver", "Angle Grinder", "Hammer Drill", "+5 more"] },
      { name: "Heavy Equipment", icon: Factory, count: 8, items: ["Forklift", "Excavator", "Loader", "+6 more"] },
      { name: "Automation", icon: Cpu, count: 7, items: ["PLC", "Sensors", "Robotics", "Actuators", "+4 more"] },
    ],
  },
  {
    id: "hardware",
    name: "Hardware",
    icon: Hammer,
    accent: "#F59E0B",
    count: 81,
    subcategories: [
      { name: "Hand Tools", icon: Hammer, count: 12, items: ["Hammers", "Screwdrivers", "Pliers", "Wrenches", "+8 more"] },
      { name: "Power Tools", icon: Drill, count: 11, items: ["Drills", "Saws", "Grinders", "+8 more"] },
      { name: "Fasteners", icon: Wrench, count: 9, items: ["Bolts", "Nuts", "Screws", "Washers", "+6 more"] },
      { name: "Plumbing", icon: Wrench, count: 10, items: ["Valves", "Fittings", "Pipes", "+7 more"] },
      { name: "Electrical", icon: PlugZap, count: 14, items: ["Switches", "Breakers", "Wiring", "+10 more"] },
      { name: "Safety", icon: ShieldCheck, count: 8, items: ["Locks", "Guards", "Signage", "+5 more"] },
      { name: "Storage", icon: Boxes, count: 9, items: ["Shelving", "Bins", "Racks", "+6 more"] },
      { name: "Consumables", icon: Package, count: 8, items: ["Tapes", "Blades", "Abrasives", "+5 more"] },
    ],
  },
  {
    id: "electronics",
    name: "Electronics",
    icon: Monitor,
    accent: "#8B5CF6",
    count: 92,
    subcategories: [
      { name: "Laptops", icon: Monitor, count: 15, items: ["Ultrabook", "Workstation", "Chromebook", "+12 more"] },
      { name: "Phones", icon: Smartphone, count: 18, items: ["Android", "iOS", "Rugged", "+15 more"] },
      { name: "Tablets", icon: Tablet, count: 11, items: ["Business Tablet", "Rugged Tablet", "+8 more"] },
      { name: "Components", icon: Cpu, count: 14, items: ["CPU", "GPU", "RAM", "SSD", "+10 more"] },
      { name: "Networking", icon: Globe, count: 9, items: ["Routers", "Switches", "APs", "+6 more"] },
      { name: "Audio", icon: Sparkles, count: 8, items: ["Headphones", "Speakers", "+5 more"] },
      { name: "Cameras", icon: Eye, count: 7, items: ["IP Cameras", "DSLR", "+4 more"] },
      { name: "Accessories", icon: Package, count: 10, items: ["Cables", "Adapters", "+7 more"] },
    ],
  },
  {
    id: "furniture",
    name: "Furniture",
    icon: Sofa,
    accent: "#F97316",
    count: 76,
    subcategories: [
      { name: "Sofas", icon: Sofa, count: 12, items: ["Sectional", "Sleeper", "Leather", "+9 more"] },
      { name: "Tables", icon: Table, count: 11, items: ["Dining", "Coffee", "Work", "+8 more"] },
      { name: "Chairs", icon: Armchair, count: 13, items: ["Office", "Dining", "Lounge", "+10 more"] },
      { name: "Beds", icon: BedDouble, count: 8, items: ["Platform", "Storage", "+5 more"] },
      { name: "Storage", icon: Boxes, count: 10, items: ["Cabinets", "Shelves", "+7 more"] },
      { name: "Lighting", icon: Sun, count: 7, items: ["Pendant", "Floor", "+4 more"] },
      { name: "Decor", icon: Sparkles, count: 9, items: ["Rugs", "Art", "+6 more"] },
      { name: "Office", icon: Building2, count: 6, items: ["Desks", "Conference", "+3 more"] },
    ],
  },
  {
    id: "energy",
    name: "Energy",
    icon: Sun,
    accent: "#FBBF24",
    count: 61,
    subcategories: [
      { name: "Solar Panels", icon: Sun, count: 18, items: ["Mono", "Poly", "Bifacial", "+15 more"] },
      { name: "Batteries", icon: BatteryCharging, count: 12, items: ["LiFePO4", "AGM", "+9 more"] },
      { name: "Inverters", icon: Zap, count: 9, items: ["Hybrid", "On-grid", "Off-grid", "+6 more"] },
      { name: "EV Charging", icon: PlugZap, count: 7, items: ["Wallbox", "Fast Charger", "+4 more"] },
      { name: "Energy Storage", icon: Boxes, count: 8, items: ["Home ESS", "Rack ESS", "+5 more"] },
      { name: "Accessories", icon: Package, count: 7, items: ["Cables", "Mounts", "+4 more"] },
    ],
  },
  {
    id: "apparel",
    name: "Apparel",
    icon: Shirt,
    accent: "#FB7185",
    count: 149,
    subcategories: [
      { name: "Men's Wear", icon: User, count: 35, items: ["Shirts", "Pants", "Jackets", "+32 more"] },
      { name: "Women's Wear", icon: User, count: 41, items: ["Dresses", "Tops", "Jeans", "+38 more"] },
      { name: "Kids", icon: User, count: 18, items: ["T-Shirts", "Shorts", "+15 more"] },
      { name: "Workwear", icon: HardHat, count: 16, items: ["Safety Jackets", "Boots", "+13 more"] },
      { name: "Footwear", icon: Footprints, count: 15, items: ["Sneakers", "Boots", "+12 more"] },
      { name: "Accessories", icon: Package, count: 24, items: ["Belts", "Bags", "+21 more"] },
      { name: "Sportswear", icon: Dumbbell, count: 12, items: ["Active Tops", "Leggings", "+9 more"] },
      { name: "Outerwear", icon: Shirt, count: 12, items: ["Coats", "Puffer", "+9 more"] },
      { name: "Uniforms", icon: Building2, count: 16, items: ["Hospitality", "School", "+13 more"] },
      { name: "Underwear", icon: Shirt, count: 10, items: ["Basics", "Sets", "+7 more"] },
      { name: "Swim", icon: Sparkles, count: 8, items: ["One-piece", "Trunks", "+5 more"] },
      { name: "Traditional", icon: Leaf, count: 7, items: ["Kurta", "Abaya", "+4 more"] },
      { name: "Streetwear", icon: Sparkles, count: 9, items: ["Hoodies", "Caps", "+6 more"] },
      { name: "Luxury", icon: Sparkles, count: 8, items: ["Designer", "Limited", "+5 more"] },
    ],
  },
  {
    id: "beauty",
    name: "Beauty",
    icon: Palette,
    accent: "#EC4899",
    count: 58,
    subcategories: [
      { name: "Skincare", icon: Sparkles, count: 18, items: ["Cleanser", "Serum", "SPF", "+15 more"] },
      { name: "Makeup", icon: Palette, count: 16, items: ["Foundation", "Mascara", "+13 more"] },
      { name: "Haircare", icon: Sparkles, count: 12, items: ["Shampoo", "Oil", "+9 more"] },
      { name: "Fragrance", icon: Sparkles, count: 5, items: ["EDP", "EDT", "+2 more"] },
      { name: "Tools", icon: Wrench, count: 4, items: ["Brushes", "Sponges", "+1 more"] },
      { name: "Wellness", icon: Leaf, count: 3, items: ["Supplements", "+0 more"] },
    ],
  },
  {
    id: "mining",
    name: "Mining",
    icon: Gem,
    accent: "#3B82F6",
    count: 64,
    subcategories: [
      { name: "Minerals", icon: Gem, count: 14, items: ["Copper Ore", "Bauxite", "+11 more"] },
      { name: "Equipment", icon: Pickaxe, count: 16, items: ["Drills", "Loaders", "+13 more"] },
      { name: "Safety", icon: ShieldCheck, count: 9, items: ["Helmets", "Sensors", "+6 more"] },
      { name: "Tools", icon: Hammer, count: 8, items: ["Pickaxe", "Shovels", "+5 more"] },
      { name: "Logistics", icon: Truck, count: 9, items: ["Haul Trucks", "+6 more"] },
      { name: "Services", icon: Mountain, count: 8, items: ["Survey", "Maintenance", "+5 more"] },
    ],
  },
  {
    id: "agriculture",
    name: "Agriculture",
    icon: Wheat,
    accent: "#22C55E",
    count: 72,
    subcategories: [
      { name: "Produce", icon: Leaf, count: 18, items: ["Mango", "Avocado", "+15 more"] },
      { name: "Equipment", icon: Tractor, count: 14, items: ["Tractor", "Seeder", "+11 more"] },
      { name: "Irrigation", icon: Droplets, count: 10, items: ["Drip", "Sprinkler", "+7 more"] },
      { name: "Fertilizer", icon: FlaskConical, count: 12, items: ["NPK", "Organic", "+9 more"] },
      { name: "Grains", icon: Wheat, count: 9, items: ["Rice", "Wheat", "+6 more"] },
      { name: "Livestock", icon: PawPrint, count: 9, items: ["Feed", "Supplements", "+6 more"] },
    ],
  },
  {
    id: "sports",
    name: "Sports",
    icon: Volleyball,
    accent: "#14B8A6",
    count: 55,
    subcategories: [
      { name: "Equipment", icon: Dumbbell, count: 18, items: ["Dumbbells", "Bands", "+15 more"] },
      { name: "Outdoor", icon: Mountain, count: 10, items: ["Camping", "Hiking", "+7 more"] },
      { name: "Team Sports", icon: Trophy, count: 9, items: ["Football", "Basketball", "+6 more"] },
      { name: "Fitness", icon: Dumbbell, count: 8, items: ["Mats", "Kettlebells", "+5 more"] },
      { name: "Accessories", icon: Package, count: 6, items: ["Bottles", "Bags", "+3 more"] },
      { name: "Wearables", icon: Watch, count: 4, items: ["Smartwatch", "+1 more"] },
    ],
  },
];

export const homeNavOrder = [
  "vehicles",
  "industrial",
  "hardware",
  "electronics",
  "furniture",
  "energy",
  "apparel",
  "beauty",
  "mining",
  "agriculture",
  "sports",
] as const;
